package com.general.hibernate.views;
// Generated 06/01/2018 10:05:31 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;




/**
 * ViSicpers generated by hbm2java
 */
public class ViSicpers  implements java.io.Serializable {


    private Date fecDesde;
     private Date fecHasta;
     private Date fecCreacion;
     private BigDecimal idCreador;
     private String desCreador;
     private BigDecimal idTrolcreador;
     private String codTrolpers;
     private String desTrolcreador;
     private BigDecimal idPers;
     private String desPers;
     private BigDecimal idTipoiden;
     private String codIden;
     private String desTipoiden;
     private String desPrimnomb;
     private String desSegunomb;
     private String desApelpate;
     private String desApelmate;
     private String desPersorga;
     private BigDecimal idTrolpers;
     private String desTrolpers;
     private BigDecimal idEstapers;
     private String desEstapers;
     private Date fecDesdeesta;
     private String desUbigeo;
     private BigDecimal idTipopers;
     private String desTipopers;
     private Date fecNaci;
     private BigDecimal idEstacivil;
     private String desEstacivil;
     private String desGrupempr;
     private String mail;
     private String telecelular;
     private String telefijo;
     private String desDireccion;
     private BigDecimal idTipovia;
     private String desTipovia;
     private String desVia;
     private BigDecimal idTipozona;
     private String desTipozona;
     private String desZona;
     private String numDire;
     private String numInterior;
     private String desDistrito;
     private String desProvincia;
     private String desDepartamento;
     private String codNumdire;
     private String codNuminterior;

    public ViSicpers() {
    }

	
    public ViSicpers(BigDecimal idPers, BigDecimal idTipoiden, String codIden) {
        this.idPers = idPers;
        this.idTipoiden = idTipoiden;
        this.codIden = codIden;
    }
    public ViSicpers(Date fecDesde, Date fecHasta, Date fecCreacion, BigDecimal idCreador, String desCreador, BigDecimal idTrolcreador, String desTrolcreador, BigDecimal idPers, String desPers, BigDecimal idTipoiden, String codIden, String desTipoiden, String desPrimnomb, String desSegunomb, String desApelpate, String desApelmate, String desPersorga, BigDecimal idTrolpers, String desTrolpers, BigDecimal idEstapers, String desEstapers, Date fecDesdeesta, String desUbigeo, BigDecimal idTipopers, String desTipopers, Date fecNaci, BigDecimal idEstacivil, String desEstacivil, String desGrupempr, String mail, String telecelular, String telefijo, String desDireccion, BigDecimal idTipovia, String desTipovia, String desVia, BigDecimal idTipozona, String desTipozona, String desZona, String numDire, String numInterior, String desDistrito, String desProvincia, String desDepartamento, String codNumdire, String codNuminterior) {
       this.fecDesde = fecDesde;
       this.fecHasta = fecHasta;
       this.fecCreacion = fecCreacion;
       this.idCreador = idCreador;
       this.desCreador = desCreador;
       this.idTrolcreador = idTrolcreador;
       this.desTrolcreador = desTrolcreador;
       this.idPers = idPers;
       this.desPers = desPers;
       this.idTipoiden = idTipoiden;
       this.codIden = codIden;
       this.desTipoiden = desTipoiden;
       this.desPrimnomb = desPrimnomb;
       this.desSegunomb = desSegunomb;
       this.desApelpate = desApelpate;
       this.desApelmate = desApelmate;
       this.desPersorga = desPersorga;
       this.idTrolpers = idTrolpers;
       this.desTrolpers = desTrolpers;
       this.idEstapers = idEstapers;
       this.desEstapers = desEstapers;
       this.fecDesdeesta = fecDesdeesta;
       this.desUbigeo = desUbigeo;
       this.idTipopers = idTipopers;
       this.desTipopers = desTipopers;
       this.fecNaci = fecNaci;
       this.idEstacivil = idEstacivil;
       this.desEstacivil = desEstacivil;
       this.desGrupempr = desGrupempr;
       this.mail = mail;
       this.telecelular = telecelular;
       this.telefijo = telefijo;
       this.desDireccion = desDireccion;
       this.idTipovia = idTipovia;
       this.desTipovia = desTipovia;
       this.desVia = desVia;
       this.idTipozona = idTipozona;
       this.desTipozona = desTipozona;
       this.desZona = desZona;
       this.numDire = numDire;
       this.numInterior = numInterior;
       this.desDistrito = desDistrito;
       this.desProvincia = desProvincia;
       this.desDepartamento = desDepartamento;
       this.codNumdire = codNumdire;
       this.codNuminterior = codNuminterior;
    }
   
    public Date getFecDesde() {
        return this.fecDesde;
    }
    
    public void setFecDesde(Date fecDesde) {
        this.fecDesde = fecDesde;
    }
    public Date getFecHasta() {
        return this.fecHasta;
    }
    
    public void setFecHasta(Date fecHasta) {
        this.fecHasta = fecHasta;
    }
    public Date getFecCreacion() {
        return this.fecCreacion;
    }
    
    public void setFecCreacion(Date fecCreacion) {
        this.fecCreacion = fecCreacion;
    }
    public BigDecimal getIdCreador() {
        return this.idCreador;
    }
    
    public void setIdCreador(BigDecimal idCreador) {
        this.idCreador = idCreador;
    }
    public String getDesCreador() {
        return this.desCreador;
    }
    
    public void setDesCreador(String desCreador) {
        this.desCreador = desCreador;
    }
    public BigDecimal getIdTrolcreador() {
        return this.idTrolcreador;
    }
    
    public void setIdTrolcreador(BigDecimal idTrolcreador) {
        this.idTrolcreador = idTrolcreador;
    }

    public String getCodTrolpers() {
        return codTrolpers;
    }

    public void setCodTrolpers(String codTrolpers) {
        this.codTrolpers = codTrolpers;
    }
    
    public String getDesTrolcreador() {
        return this.desTrolcreador;
    }
    
    public void setDesTrolcreador(String desTrolcreador) {
        this.desTrolcreador = desTrolcreador;
    }
    public BigDecimal getIdPers() {
        return this.idPers;
    }
    
    public void setIdPers(BigDecimal idPers) {
        this.idPers = idPers;
    }
    public String getDesPers() {
        return this.desPers;
    }
    
    public void setDesPers(String desPers) {
        this.desPers = desPers;
    }
    public BigDecimal getIdTipoiden() {
        return this.idTipoiden;
    }
    
    public void setIdTipoiden(BigDecimal idTipoiden) {
        this.idTipoiden = idTipoiden;
    }
    public String getCodIden() {
        return this.codIden;
    }
    
    public void setCodIden(String codIden) {
        this.codIden = codIden;
    }
    public String getDesTipoiden() {
        return this.desTipoiden;
    }
    
    public void setDesTipoiden(String desTipoiden) {
        this.desTipoiden = desTipoiden;
    }
    public String getDesPrimnomb() {
        return this.desPrimnomb;
    }
    
    public void setDesPrimnomb(String desPrimnomb) {
        this.desPrimnomb = desPrimnomb;
    }
    public String getDesSegunomb() {
        return this.desSegunomb;
    }
    
    public void setDesSegunomb(String desSegunomb) {
        this.desSegunomb = desSegunomb;
    }
    public String getDesApelpate() {
        return this.desApelpate;
    }
    
    public void setDesApelpate(String desApelpate) {
        this.desApelpate = desApelpate;
    }
    public String getDesApelmate() {
        return this.desApelmate;
    }
    
    public void setDesApelmate(String desApelmate) {
        this.desApelmate = desApelmate;
    }
    public String getDesPersorga() {
        return this.desPersorga;
    }
    
    public void setDesPersorga(String desPersorga) {
        this.desPersorga = desPersorga;
    }
    public BigDecimal getIdTrolpers() {
        return this.idTrolpers;
    }
    
    public void setIdTrolpers(BigDecimal idTrolpers) {
        this.idTrolpers = idTrolpers;
    }
    public String getDesTrolpers() {
        return this.desTrolpers;
    }
    
    public void setDesTrolpers(String desTrolpers) {
        this.desTrolpers = desTrolpers;
    }
    public BigDecimal getIdEstapers() {
        return this.idEstapers;
    }
    
    public void setIdEstapers(BigDecimal idEstapers) {
        this.idEstapers = idEstapers;
    }
    public String getDesEstapers() {
        return this.desEstapers;
    }
    
    public void setDesEstapers(String desEstapers) {
        this.desEstapers = desEstapers;
    }
    public Date getFecDesdeesta() {
        return this.fecDesdeesta;
    }
    
    public void setFecDesdeesta(Date fecDesdeesta) {
        this.fecDesdeesta = fecDesdeesta;
    }
    public String getDesUbigeo() {
        return this.desUbigeo;
    }
    
    public void setDesUbigeo(String desUbigeo) {
        this.desUbigeo = desUbigeo;
    }
    public BigDecimal getIdTipopers() {
        return this.idTipopers;
    }
    
    public void setIdTipopers(BigDecimal idTipopers) {
        this.idTipopers = idTipopers;
    }
    public String getDesTipopers() {
        return this.desTipopers;
    }
    
    public void setDesTipopers(String desTipopers) {
        this.desTipopers = desTipopers;
    }
    public Date getFecNaci() {
        return this.fecNaci;
    }
    
    public void setFecNaci(Date fecNaci) {
        this.fecNaci = fecNaci;
    }
    public BigDecimal getIdEstacivil() {
        return this.idEstacivil;
    }
    
    public void setIdEstacivil(BigDecimal idEstacivil) {
        this.idEstacivil = idEstacivil;
    }
    public String getDesEstacivil() {
        return this.desEstacivil;
    }
    
    public void setDesEstacivil(String desEstacivil) {
        this.desEstacivil = desEstacivil;
    }
    public String getDesGrupempr() {
        return this.desGrupempr;
    }
    
    public void setDesGrupempr(String desGrupempr) {
        this.desGrupempr = desGrupempr;
    }
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }
    public String getTelecelular() {
        return this.telecelular;
    }
    
    public void setTelecelular(String telecelular) {
        this.telecelular = telecelular;
    }
    public String getTelefijo() {
        return this.telefijo;
    }
    
    public void setTelefijo(String telefijo) {
        this.telefijo = telefijo;
    }
    public String getDesDireccion() {
        return this.desDireccion;
    }
    
    public void setDesDireccion(String desDireccion) {
        this.desDireccion = desDireccion;
    }
    public BigDecimal getIdTipovia() {
        return this.idTipovia;
    }
    
    public void setIdTipovia(BigDecimal idTipovia) {
        this.idTipovia = idTipovia;
    }
    public String getDesTipovia() {
        return this.desTipovia;
    }
    
    public void setDesTipovia(String desTipovia) {
        this.desTipovia = desTipovia;
    }
    public String getDesVia() {
        return this.desVia;
    }
    
    public void setDesVia(String desVia) {
        this.desVia = desVia;
    }
    public BigDecimal getIdTipozona() {
        return this.idTipozona;
    }
    
    public void setIdTipozona(BigDecimal idTipozona) {
        this.idTipozona = idTipozona;
    }
    public String getDesTipozona() {
        return this.desTipozona;
    }
    
    public void setDesTipozona(String desTipozona) {
        this.desTipozona = desTipozona;
    }
    public String getDesZona() {
        return this.desZona;
    }
    
    public void setDesZona(String desZona) {
        this.desZona = desZona;
    }
    public String getNumDire() {
        return this.numDire;
    }
    
    public void setNumDire(String numDire) {
        this.numDire = numDire;
    }
    public String getNumInterior() {
        return this.numInterior;
    }
    
    public void setNumInterior(String numInterior) {
        this.numInterior = numInterior;
    }
    public String getDesDistrito() {
        return this.desDistrito;
    }
    
    public void setDesDistrito(String desDistrito) {
        this.desDistrito = desDistrito;
    }
    public String getDesProvincia() {
        return this.desProvincia;
    }
    
    public void setDesProvincia(String desProvincia) {
        this.desProvincia = desProvincia;
    }
    public String getDesDepartamento() {
        return this.desDepartamento;
    }
    
    public void setDesDepartamento(String desDepartamento) {
        this.desDepartamento = desDepartamento;
    }
    public String getCodNumdire() {
        return this.codNumdire;
    }
    
    public void setCodNumdire(String codNumdire) {
        this.codNumdire = codNumdire;
    }
    public String getCodNuminterior() {
        return this.codNuminterior;
    }
    
    public void setCodNuminterior(String codNuminterior) {
        this.codNuminterior = codNuminterior;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ViSicpers) ) return false;
		 ViSicpers castOther = ( ViSicpers ) other; 
         
		 return ( (this.getFecDesde()==castOther.getFecDesde()) || ( this.getFecDesde()!=null && castOther.getFecDesde()!=null && this.getFecDesde().equals(castOther.getFecDesde()) ) )
 && ( (this.getFecHasta()==castOther.getFecHasta()) || ( this.getFecHasta()!=null && castOther.getFecHasta()!=null && this.getFecHasta().equals(castOther.getFecHasta()) ) )
 && ( (this.getFecCreacion()==castOther.getFecCreacion()) || ( this.getFecCreacion()!=null && castOther.getFecCreacion()!=null && this.getFecCreacion().equals(castOther.getFecCreacion()) ) )
 && ( (this.getIdCreador()==castOther.getIdCreador()) || ( this.getIdCreador()!=null && castOther.getIdCreador()!=null && this.getIdCreador().equals(castOther.getIdCreador()) ) )
 && ( (this.getDesCreador()==castOther.getDesCreador()) || ( this.getDesCreador()!=null && castOther.getDesCreador()!=null && this.getDesCreador().equals(castOther.getDesCreador()) ) )
 && ( (this.getIdTrolcreador()==castOther.getIdTrolcreador()) || ( this.getIdTrolcreador()!=null && castOther.getIdTrolcreador()!=null && this.getIdTrolcreador().equals(castOther.getIdTrolcreador()) ) )
 && ( (this.getDesTrolcreador()==castOther.getDesTrolcreador()) || ( this.getDesTrolcreador()!=null && castOther.getDesTrolcreador()!=null && this.getDesTrolcreador().equals(castOther.getDesTrolcreador()) ) )
 && ( (this.getIdPers()==castOther.getIdPers()) || ( this.getIdPers()!=null && castOther.getIdPers()!=null && this.getIdPers().equals(castOther.getIdPers()) ) )
 && ( (this.getDesPers()==castOther.getDesPers()) || ( this.getDesPers()!=null && castOther.getDesPers()!=null && this.getDesPers().equals(castOther.getDesPers()) ) )
 && ( (this.getIdTipoiden()==castOther.getIdTipoiden()) || ( this.getIdTipoiden()!=null && castOther.getIdTipoiden()!=null && this.getIdTipoiden().equals(castOther.getIdTipoiden()) ) )
 && ( (this.getCodIden()==castOther.getCodIden()) || ( this.getCodIden()!=null && castOther.getCodIden()!=null && this.getCodIden().equals(castOther.getCodIden()) ) )
 && ( (this.getDesTipoiden()==castOther.getDesTipoiden()) || ( this.getDesTipoiden()!=null && castOther.getDesTipoiden()!=null && this.getDesTipoiden().equals(castOther.getDesTipoiden()) ) )
 && ( (this.getDesPrimnomb()==castOther.getDesPrimnomb()) || ( this.getDesPrimnomb()!=null && castOther.getDesPrimnomb()!=null && this.getDesPrimnomb().equals(castOther.getDesPrimnomb()) ) )
 && ( (this.getDesSegunomb()==castOther.getDesSegunomb()) || ( this.getDesSegunomb()!=null && castOther.getDesSegunomb()!=null && this.getDesSegunomb().equals(castOther.getDesSegunomb()) ) )
 && ( (this.getDesApelpate()==castOther.getDesApelpate()) || ( this.getDesApelpate()!=null && castOther.getDesApelpate()!=null && this.getDesApelpate().equals(castOther.getDesApelpate()) ) )
 && ( (this.getDesApelmate()==castOther.getDesApelmate()) || ( this.getDesApelmate()!=null && castOther.getDesApelmate()!=null && this.getDesApelmate().equals(castOther.getDesApelmate()) ) )
 && ( (this.getDesPersorga()==castOther.getDesPersorga()) || ( this.getDesPersorga()!=null && castOther.getDesPersorga()!=null && this.getDesPersorga().equals(castOther.getDesPersorga()) ) )
 && ( (this.getIdTrolpers()==castOther.getIdTrolpers()) || ( this.getIdTrolpers()!=null && castOther.getIdTrolpers()!=null && this.getIdTrolpers().equals(castOther.getIdTrolpers()) ) )
 && ( (this.getDesTrolpers()==castOther.getDesTrolpers()) || ( this.getDesTrolpers()!=null && castOther.getDesTrolpers()!=null && this.getDesTrolpers().equals(castOther.getDesTrolpers()) ) )
 && ( (this.getIdEstapers()==castOther.getIdEstapers()) || ( this.getIdEstapers()!=null && castOther.getIdEstapers()!=null && this.getIdEstapers().equals(castOther.getIdEstapers()) ) )
 && ( (this.getDesEstapers()==castOther.getDesEstapers()) || ( this.getDesEstapers()!=null && castOther.getDesEstapers()!=null && this.getDesEstapers().equals(castOther.getDesEstapers()) ) )
 && ( (this.getFecDesdeesta()==castOther.getFecDesdeesta()) || ( this.getFecDesdeesta()!=null && castOther.getFecDesdeesta()!=null && this.getFecDesdeesta().equals(castOther.getFecDesdeesta()) ) )
 && ( (this.getDesUbigeo()==castOther.getDesUbigeo()) || ( this.getDesUbigeo()!=null && castOther.getDesUbigeo()!=null && this.getDesUbigeo().equals(castOther.getDesUbigeo()) ) )
 && ( (this.getIdTipopers()==castOther.getIdTipopers()) || ( this.getIdTipopers()!=null && castOther.getIdTipopers()!=null && this.getIdTipopers().equals(castOther.getIdTipopers()) ) )
 && ( (this.getDesTipopers()==castOther.getDesTipopers()) || ( this.getDesTipopers()!=null && castOther.getDesTipopers()!=null && this.getDesTipopers().equals(castOther.getDesTipopers()) ) )
 && ( (this.getFecNaci()==castOther.getFecNaci()) || ( this.getFecNaci()!=null && castOther.getFecNaci()!=null && this.getFecNaci().equals(castOther.getFecNaci()) ) )
 && ( (this.getIdEstacivil()==castOther.getIdEstacivil()) || ( this.getIdEstacivil()!=null && castOther.getIdEstacivil()!=null && this.getIdEstacivil().equals(castOther.getIdEstacivil()) ) )
 && ( (this.getDesEstacivil()==castOther.getDesEstacivil()) || ( this.getDesEstacivil()!=null && castOther.getDesEstacivil()!=null && this.getDesEstacivil().equals(castOther.getDesEstacivil()) ) )
 && ( (this.getDesGrupempr()==castOther.getDesGrupempr()) || ( this.getDesGrupempr()!=null && castOther.getDesGrupempr()!=null && this.getDesGrupempr().equals(castOther.getDesGrupempr()) ) )
 && ( (this.getMail()==castOther.getMail()) || ( this.getMail()!=null && castOther.getMail()!=null && this.getMail().equals(castOther.getMail()) ) )
 && ( (this.getTelecelular()==castOther.getTelecelular()) || ( this.getTelecelular()!=null && castOther.getTelecelular()!=null && this.getTelecelular().equals(castOther.getTelecelular()) ) )
 && ( (this.getTelefijo()==castOther.getTelefijo()) || ( this.getTelefijo()!=null && castOther.getTelefijo()!=null && this.getTelefijo().equals(castOther.getTelefijo()) ) )
 && ( (this.getDesDireccion()==castOther.getDesDireccion()) || ( this.getDesDireccion()!=null && castOther.getDesDireccion()!=null && this.getDesDireccion().equals(castOther.getDesDireccion()) ) )
 && ( (this.getIdTipovia()==castOther.getIdTipovia()) || ( this.getIdTipovia()!=null && castOther.getIdTipovia()!=null && this.getIdTipovia().equals(castOther.getIdTipovia()) ) )
 && ( (this.getDesTipovia()==castOther.getDesTipovia()) || ( this.getDesTipovia()!=null && castOther.getDesTipovia()!=null && this.getDesTipovia().equals(castOther.getDesTipovia()) ) )
 && ( (this.getDesVia()==castOther.getDesVia()) || ( this.getDesVia()!=null && castOther.getDesVia()!=null && this.getDesVia().equals(castOther.getDesVia()) ) )
 && ( (this.getIdTipozona()==castOther.getIdTipozona()) || ( this.getIdTipozona()!=null && castOther.getIdTipozona()!=null && this.getIdTipozona().equals(castOther.getIdTipozona()) ) )
 && ( (this.getDesTipozona()==castOther.getDesTipozona()) || ( this.getDesTipozona()!=null && castOther.getDesTipozona()!=null && this.getDesTipozona().equals(castOther.getDesTipozona()) ) )
 && ( (this.getDesZona()==castOther.getDesZona()) || ( this.getDesZona()!=null && castOther.getDesZona()!=null && this.getDesZona().equals(castOther.getDesZona()) ) )
 && ( (this.getNumDire()==castOther.getNumDire()) || ( this.getNumDire()!=null && castOther.getNumDire()!=null && this.getNumDire().equals(castOther.getNumDire()) ) )
 && ( (this.getNumInterior()==castOther.getNumInterior()) || ( this.getNumInterior()!=null && castOther.getNumInterior()!=null && this.getNumInterior().equals(castOther.getNumInterior()) ) )
 && ( (this.getDesDistrito()==castOther.getDesDistrito()) || ( this.getDesDistrito()!=null && castOther.getDesDistrito()!=null && this.getDesDistrito().equals(castOther.getDesDistrito()) ) )
 && ( (this.getDesProvincia()==castOther.getDesProvincia()) || ( this.getDesProvincia()!=null && castOther.getDesProvincia()!=null && this.getDesProvincia().equals(castOther.getDesProvincia()) ) )
 && ( (this.getDesDepartamento()==castOther.getDesDepartamento()) || ( this.getDesDepartamento()!=null && castOther.getDesDepartamento()!=null && this.getDesDepartamento().equals(castOther.getDesDepartamento()) ) )
 && ( (this.getCodNumdire()==castOther.getCodNumdire()) || ( this.getCodNumdire()!=null && castOther.getCodNumdire()!=null && this.getCodNumdire().equals(castOther.getCodNumdire()) ) )
 && ( (this.getCodNuminterior()==castOther.getCodNuminterior()) || ( this.getCodNuminterior()!=null && castOther.getCodNuminterior()!=null && this.getCodNuminterior().equals(castOther.getCodNuminterior()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getFecDesde() == null ? 0 : this.getFecDesde().hashCode() );
         result = 37 * result + ( getFecHasta() == null ? 0 : this.getFecHasta().hashCode() );
         result = 37 * result + ( getFecCreacion() == null ? 0 : this.getFecCreacion().hashCode() );
         result = 37 * result + ( getIdCreador() == null ? 0 : this.getIdCreador().hashCode() );
         result = 37 * result + ( getDesCreador() == null ? 0 : this.getDesCreador().hashCode() );
         result = 37 * result + ( getIdTrolcreador() == null ? 0 : this.getIdTrolcreador().hashCode() );
         result = 37 * result + ( getDesTrolcreador() == null ? 0 : this.getDesTrolcreador().hashCode() );
         result = 37 * result + ( getIdPers() == null ? 0 : this.getIdPers().hashCode() );
         result = 37 * result + ( getDesPers() == null ? 0 : this.getDesPers().hashCode() );
         result = 37 * result + ( getIdTipoiden() == null ? 0 : this.getIdTipoiden().hashCode() );
         result = 37 * result + ( getCodIden() == null ? 0 : this.getCodIden().hashCode() );
         result = 37 * result + ( getDesTipoiden() == null ? 0 : this.getDesTipoiden().hashCode() );
         result = 37 * result + ( getDesPrimnomb() == null ? 0 : this.getDesPrimnomb().hashCode() );
         result = 37 * result + ( getDesSegunomb() == null ? 0 : this.getDesSegunomb().hashCode() );
         result = 37 * result + ( getDesApelpate() == null ? 0 : this.getDesApelpate().hashCode() );
         result = 37 * result + ( getDesApelmate() == null ? 0 : this.getDesApelmate().hashCode() );
         result = 37 * result + ( getDesPersorga() == null ? 0 : this.getDesPersorga().hashCode() );
         result = 37 * result + ( getIdTrolpers() == null ? 0 : this.getIdTrolpers().hashCode() );
         result = 37 * result + ( getDesTrolpers() == null ? 0 : this.getDesTrolpers().hashCode() );
         result = 37 * result + ( getIdEstapers() == null ? 0 : this.getIdEstapers().hashCode() );
         result = 37 * result + ( getDesEstapers() == null ? 0 : this.getDesEstapers().hashCode() );
         result = 37 * result + ( getFecDesdeesta() == null ? 0 : this.getFecDesdeesta().hashCode() );
         result = 37 * result + ( getDesUbigeo() == null ? 0 : this.getDesUbigeo().hashCode() );
         result = 37 * result + ( getIdTipopers() == null ? 0 : this.getIdTipopers().hashCode() );
         result = 37 * result + ( getDesTipopers() == null ? 0 : this.getDesTipopers().hashCode() );
         result = 37 * result + ( getFecNaci() == null ? 0 : this.getFecNaci().hashCode() );
         result = 37 * result + ( getIdEstacivil() == null ? 0 : this.getIdEstacivil().hashCode() );
         result = 37 * result + ( getDesEstacivil() == null ? 0 : this.getDesEstacivil().hashCode() );
         result = 37 * result + ( getDesGrupempr() == null ? 0 : this.getDesGrupempr().hashCode() );
         result = 37 * result + ( getMail() == null ? 0 : this.getMail().hashCode() );
         result = 37 * result + ( getTelecelular() == null ? 0 : this.getTelecelular().hashCode() );
         result = 37 * result + ( getTelefijo() == null ? 0 : this.getTelefijo().hashCode() );
         result = 37 * result + ( getDesDireccion() == null ? 0 : this.getDesDireccion().hashCode() );
         result = 37 * result + ( getIdTipovia() == null ? 0 : this.getIdTipovia().hashCode() );
         result = 37 * result + ( getDesTipovia() == null ? 0 : this.getDesTipovia().hashCode() );
         result = 37 * result + ( getDesVia() == null ? 0 : this.getDesVia().hashCode() );
         result = 37 * result + ( getIdTipozona() == null ? 0 : this.getIdTipozona().hashCode() );
         result = 37 * result + ( getDesTipozona() == null ? 0 : this.getDesTipozona().hashCode() );
         result = 37 * result + ( getDesZona() == null ? 0 : this.getDesZona().hashCode() );
         result = 37 * result + ( getNumDire() == null ? 0 : this.getNumDire().hashCode() );
         result = 37 * result + ( getNumInterior() == null ? 0 : this.getNumInterior().hashCode() );
         result = 37 * result + ( getDesDistrito() == null ? 0 : this.getDesDistrito().hashCode() );
         result = 37 * result + ( getDesProvincia() == null ? 0 : this.getDesProvincia().hashCode() );
         result = 37 * result + ( getDesDepartamento() == null ? 0 : this.getDesDepartamento().hashCode() );
         result = 37 * result + ( getCodNumdire() == null ? 0 : this.getCodNumdire().hashCode() );
         result = 37 * result + ( getCodNuminterior() == null ? 0 : this.getCodNuminterior().hashCode() );
         return result;
   }
}


