package com.general.hibernate.views;
// Generated 27/12/2017 03:16:27 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;


/**
 * ViSicdocu generated by hbm2java
 */
public class ViSicdocu  implements java.io.Serializable {


    private BigDecimal idDocu;
    private String codIden;
    private String desDocu;
    private Date fecCreacion;

    private String desModoPago;

    private BigDecimal idPersClieprov;
    private String codIdenClieprov;
    private String desPersClieprov;
    private BigDecimal idTrolpersClieprov;
    private String desTrolpersClieprov;

    private BigDecimal idClaseeven;
    private String codClaseeven;
    private String desClaseeven;

    private BigDecimal idSclaseeven;
    private String codSclaseeven;
    private String desSclaseeven;

    private BigDecimal idStipodocu;
    private String desStipodocu;
    private String codStipodocu;
    private String codSerie;
    private BigDecimal numDocu;
    private String numDocuunido;
    private String desNotas;
    private Date fecDesde;
    private Date fecHasta;   

    private String numSubtotal;
    private String numMtoigv;
    private String numMtodscto;
    private Double numMtototal;
    
    private Double numTotalpagado;
    private Double numMtopagadotarjeta;
    private Double numMtopagadocomitarjeta;
    private Double numMtopagadoefectivo;

    private BigDecimal idTipodocu;
    private String desTipodocu;
    private String codTipodocu;
    private BigDecimal idEstadocu;
    private String codEsta;
    private String desEstadocu;
    private Date fecDesdeesta;
    private Date fecHastaesta;

    private BigDecimal idPersCreador;
    private String desPersCreador;
    private BigDecimal idTrolpersCreador;
    private String desTrolpersCreador;

    private BigDecimal idDocurel;
    private String desDocurel;
    private String desSucursal;
    
    private String indSitusunat;
    private String desSitusunat;
    private Date fecEnvisunat;
    
    private Integer flgDeclaradosunat;

    public ViSicdocu() {
    }

	
    public ViSicdocu(BigDecimal idDocu, String codIden) {
        this.idDocu = idDocu;
        this.codIden = codIden;
    }
    public ViSicdocu(BigDecimal idDocu, String codIden, String desDocu, Date fecCreacion, BigDecimal idPersCreador, String desPersCreador, BigDecimal idTrolpersCreador, String desTrolpersCreador, BigDecimal idStipodocu, String desStipodocu, String codStipodocu, String codSerie, BigDecimal numDocu, String desNotas, Date fecDesde, Date fecHasta, BigDecimal idPers, BigDecimal numSubtotal, BigDecimal numIgv, BigDecimal numTotal, BigDecimal idTipodocu, String desTipodocu, String codTipodocu, BigDecimal idEstadocu, String codEsta, String desEstadocu, Date fecDesdeesta, Date fecHastaesta) {
       this.idDocu = idDocu;
       this.codIden = codIden;
       this.desDocu = desDocu;
       this.fecCreacion = fecCreacion;
       this.idPersCreador = idPersCreador;
       this.desPersCreador = desPersCreador;
       this.idTrolpersCreador = idTrolpersCreador;
       this.desTrolpersCreador = desTrolpersCreador;
       this.idStipodocu = idStipodocu;
       this.desStipodocu = desStipodocu;
       this.codStipodocu = codStipodocu;
       this.codSerie = codSerie;
       this.numDocu = numDocu;
       this.desNotas = desNotas;
       this.fecDesde = fecDesde;
       this.fecHasta = fecHasta;       
       this.idTipodocu = idTipodocu;
       this.desTipodocu = desTipodocu;
       this.codTipodocu = codTipodocu;
       this.idEstadocu = idEstadocu;
       this.codEsta = codEsta;
       this.desEstadocu = desEstadocu;
       this.fecDesdeesta = fecDesdeesta;
       this.fecHastaesta = fecHastaesta;
    }
   
    public BigDecimal getIdDocu() {
        return this.idDocu;
    }
    
    public void setIdDocu(BigDecimal idDocu) {
        this.idDocu = idDocu;
    }
    public String getCodIden() {
        return this.codIden;
    }
    
    public void setCodIden(String codIden) {
        this.codIden = codIden;
    }
    public String getDesDocu() {
        return this.desDocu;
    }
    
    public void setDesDocu(String desDocu) {
        this.desDocu = desDocu;
    }
    public Date getFecCreacion() {
        return this.fecCreacion;
    }
    
    public void setFecCreacion(Date fecCreacion) {
        this.fecCreacion = fecCreacion;
    }
    
    /*MODALIDAD DE PAGO*/

    public String getDesModoPago() {
        return desModoPago;
    }

    public void setDesModoPago(String desModoPago) {
        this.desModoPago = desModoPago;
    }
    
    
    
    /*CLIENTE PROVEEDOR*/
    public BigDecimal getIdPersClieprov() {
        return idPersClieprov;
    }

    public void setIdPersClieprov(BigDecimal idPersClieprov) {
        this.idPersClieprov = idPersClieprov;
    }

    public String getCodIdenClieprov() {
        return codIdenClieprov;
    }

    public void setCodIdenClieprov(String codIdenClieprov) {
        this.codIdenClieprov = codIdenClieprov;
    }
    
    
    public String getDesPersClieprov() {
        return desPersClieprov;
    }

    public void setDesPersClieprov(String desPersClieprov) {
        this.desPersClieprov = desPersClieprov;
    }

    public BigDecimal getIdTrolpersClieprov() {
        return idTrolpersClieprov;
    }

    public void setIdTrolpersClieprov(BigDecimal idTrolpersClieprov) {
        this.idTrolpersClieprov = idTrolpersClieprov;
    }

    public String getDesTrolpersClieprov() {
        return desTrolpersClieprov;
    }

    public void setDesTrolpersClieprov(String desTrolpersClieprov) {
        this.desTrolpersClieprov = desTrolpersClieprov;
    }

    public BigDecimal getIdSclaseeven() {
        return idSclaseeven;
    }

    public void setIdSclaseeven(BigDecimal idSclaseeven) {
        this.idSclaseeven = idSclaseeven;
    }

    public String getCodSclaseeven() {
        return codSclaseeven;
    }

    public void setCodSclaseeven(String codSclaseeven) {
        this.codSclaseeven = codSclaseeven;
    }

    public String getDesSclaseeven() {
        return desSclaseeven;
    }

    public void setDesSclaseeven(String desSclaseeven) {
        this.desSclaseeven = desSclaseeven;
    }
    
    
    
    /*CREADOR*/
    
    public BigDecimal getIdPersCreador() {
        return this.idPersCreador;
    }
    
    public void setIdPersCreador(BigDecimal idPersCreador) {
        this.idPersCreador = idPersCreador;
    }
    public String getDesPersCreador() {
        return this.desPersCreador;
    }
    
    public void setDesPersCreador(String desPersCreador) {
        this.desPersCreador = desPersCreador;
    }
    public BigDecimal getIdTrolpersCreador() {
        return this.idTrolpersCreador;
    }
    
    public void setIdTrolpersCreador(BigDecimal idTrolpersCreador) {
        this.idTrolpersCreador = idTrolpersCreador;
    }
    public String getDesTrolpersCreador() {
        return this.desTrolpersCreador;
    }
    
    public void setDesTrolpersCreador(String desTrolpersCreador) {
        this.desTrolpersCreador = desTrolpersCreador;
    }
    public BigDecimal getIdStipodocu() {
        return this.idStipodocu;
    }
    
    public void setIdStipodocu(BigDecimal idStipodocu) {
        this.idStipodocu = idStipodocu;
    }
    public String getDesStipodocu() {
        return this.desStipodocu;
    }
    
    public void setDesStipodocu(String desStipodocu) {
        this.desStipodocu = desStipodocu;
    }
    public String getCodStipodocu() {
        return this.codStipodocu;
    }
    
    public void setCodStipodocu(String codStipodocu) {
        this.codStipodocu = codStipodocu;
    }
    public String getCodSerie() {
        return this.codSerie;
    }
    
    public void setCodSerie(String codSerie) {
        this.codSerie = codSerie;
    }
    public BigDecimal getNumDocu() {
        return this.numDocu;
    }
    
    public void setNumDocu(BigDecimal numDocu) {
        this.numDocu = numDocu;
    }

    public String getNumDocuunido() {
        return numDocuunido;
    }

    public void setNumDocuunido(String numDocuunido) {
        this.numDocuunido = numDocuunido;
    }
    
    public String getDesNotas() {
        return this.desNotas;
    }
    
    public void setDesNotas(String desNotas) {
        this.desNotas = desNotas;
    }
    public Date getFecDesde() {
        return this.fecDesde;
    }
    
    public void setFecDesde(Date fecDesde) {
        this.fecDesde = fecDesde;
    }
    public Date getFecHasta() {
        return this.fecHasta;
    }
    
    public void setFecHasta(Date fecHasta) {
        this.fecHasta = fecHasta;
    }

    public String getNumSubtotal() {
        return numSubtotal;
    }

    public void setNumSubtotal(String numSubtotal) {
        this.numSubtotal = numSubtotal;
    }

    public String getNumMtoigv() {
        return numMtoigv;
    }

    public void setNumMtoigv(String numMtoigv) {
        this.numMtoigv = numMtoigv;
    }

    public Double getNumMtototal() {
        return numMtototal;
    }

    public void setNumMtototal(Double numMtototal) {
        this.numMtototal = numMtototal;
    }

    public Double getNumTotalpagado() {
        return numTotalpagado;
    }

    public void setNumTotalpagado(Double numTotalpagado) {
        this.numTotalpagado = numTotalpagado;
    }

    public Double getNumMtopagadotarjeta() {
        return numMtopagadotarjeta;
    }

    public void setNumMtopagadotarjeta(Double numMtopagadotarjeta) {
        this.numMtopagadotarjeta = numMtopagadotarjeta;
    }

    public Double getNumMtopagadocomitarjeta() {
        return numMtopagadocomitarjeta;
    }

    public void setNumMtopagadocomitarjeta(Double numMtopagadocomitarjeta) {
        this.numMtopagadocomitarjeta = numMtopagadocomitarjeta;
    }   
    
    public Double getNumMtopagadoefectivo() {
        return numMtopagadoefectivo;
    }

    public void setNumMtopagadoefectivo(Double numMtopagadoefectivo) {
        this.numMtopagadoefectivo = numMtopagadoefectivo;
    }

   
    

    
    
    public String getNumMtodscto() {
        return numMtodscto;
    }

    public void setNumMtodscto(String numMtodscto) {
        this.numMtodscto = numMtodscto;
    }   
    
    public BigDecimal getIdTipodocu() {
        return this.idTipodocu;
    }
    
    public void setIdTipodocu(BigDecimal idTipodocu) {
        this.idTipodocu = idTipodocu;
    }
    public String getDesTipodocu() {
        return this.desTipodocu;
    }
    
    public void setDesTipodocu(String desTipodocu) {
        this.desTipodocu = desTipodocu;
    }
    public String getCodTipodocu() {
        return this.codTipodocu;
    }
    
    public void setCodTipodocu(String codTipodocu) {
        this.codTipodocu = codTipodocu;
    }
    public BigDecimal getIdEstadocu() {
        return this.idEstadocu;
    }
    
    public void setIdEstadocu(BigDecimal idEstadocu) {
        this.idEstadocu = idEstadocu;
    }
    public String getCodEsta() {
        return this.codEsta;
    }
    
    public void setCodEsta(String codEsta) {
        this.codEsta = codEsta;
    }
    public String getDesEstadocu() {
        return this.desEstadocu;
    }
    
    public void setDesEstadocu(String desEstadocu) {
        this.desEstadocu = desEstadocu;
    }
    public Date getFecDesdeesta() {
        return this.fecDesdeesta;
    }
    
    public void setFecDesdeesta(Date fecDesdeesta) {
        this.fecDesdeesta = fecDesdeesta;
    }
    public Date getFecHastaesta() {
        return this.fecHastaesta;
    }
    
    public void setFecHastaesta(Date fecHastaesta) {
        this.fecHastaesta = fecHastaesta;
    }

    public BigDecimal getIdClaseeven() {
        return idClaseeven;
    }

    public void setIdClaseeven(BigDecimal idClaseeven) {
        this.idClaseeven = idClaseeven;
    }

    public String getCodClaseeven() {
        return codClaseeven;
    }

    public void setCodClaseeven(String codClaseeven) {
        this.codClaseeven = codClaseeven;
    }

    public String getDesClaseeven() {
        return desClaseeven;
    }

    public void setDesClaseeven(String desClaseeven) {
        this.desClaseeven = desClaseeven;
    }

    public BigDecimal getIdDocurel() {
        return idDocurel;
    }

    public void setIdDocurel(BigDecimal idDocurel) {
        this.idDocurel = idDocurel;
    }       

    public String getDesDocurel() {
        return desDocurel;
    }

    public void setDesDocurel(String desDocurel) {
        this.desDocurel = desDocurel;
    }

    public String getDesSucursal() {
        return desSucursal;
    }

    public void setDesSucursal(String desSucursal) {
        this.desSucursal = desSucursal;
    }

    public String getIndSitusunat() {
        return indSitusunat;
    }

    public void setIndSitusunat(String indSitusunat) {
        this.indSitusunat = indSitusunat;
    }

    public String getDesSitusunat() {
        return desSitusunat;
    }

    public void setDesSitusunat(String desSitusunat) {
        this.desSitusunat = desSitusunat;
    }

    public Date getFecEnvisunat() {
        return fecEnvisunat;
    }

    public void setFecEnvisunat(Date fecEnvisunat) {
        this.fecEnvisunat = fecEnvisunat;
    }       

    public Integer getFlgDeclaradosunat() {
        return flgDeclaradosunat;
    }

    public void setFlgDeclaradosunat(Integer flgDeclaradosunat) {
        this.flgDeclaradosunat = flgDeclaradosunat;
    }
        
    
    
}


