package com.general.hibernate.views;
// Generated 04/01/2018 06:55:13 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;




/**
 * ViSicestageneral generated by hbm2java
 */
public class ViSicestageneral  implements java.io.Serializable {


    private BigDecimal idEsta;
     private BigDecimal idTrolesta;
     private String desEsta;
     private String codEsta;
     private Date fecDesde;
     private Date fecHasta;
     private String desNotas;
     private String codTrolesta;
     private String codClaseesta;
     private String desClaseesta;
     private BigDecimal idClaseesta;

    public ViSicestageneral() {
    }
	
    public ViSicestageneral(BigDecimal idEsta, BigDecimal idTrolesta) {
        this.idEsta = idEsta;
        this.idTrolesta = idTrolesta;
    }
    public ViSicestageneral(BigDecimal idEsta, BigDecimal idTrolesta, String desEsta, String codEsta, Date fecDesde, Date fecHasta, String desNotas, String codTrolesta, String codClaseesta, String desClaseesta, BigDecimal idClaseesta) {
       this.idEsta = idEsta;
       this.idTrolesta = idTrolesta;
       this.desEsta = desEsta;
       this.codEsta = codEsta;
       this.fecDesde = fecDesde;
       this.fecHasta = fecHasta;
       this.desNotas = desNotas;
       this.codTrolesta = codTrolesta;
       this.codClaseesta = codClaseesta;
       this.desClaseesta = desClaseesta;
       this.idClaseesta = idClaseesta;
    }
   
    public BigDecimal getIdEsta() {
        return this.idEsta;
    }
    
    public void setIdEsta(BigDecimal idEsta) {
        this.idEsta = idEsta;
    }
    public BigDecimal getIdTrolesta() {
        return this.idTrolesta;
    }
    
    public void setIdTrolesta(BigDecimal idTrolesta) {
        this.idTrolesta = idTrolesta;
    }
    public String getDesEsta() {
        return this.desEsta;
    }
    
    public void setDesEsta(String desEsta) {
        this.desEsta = desEsta;
    }
    public String getCodEsta() {
        return this.codEsta;
    }
    
    public void setCodEsta(String codEsta) {
        this.codEsta = codEsta;
    }
    public Date getFecDesde() {
        return this.fecDesde;
    }
    
    public void setFecDesde(Date fecDesde) {
        this.fecDesde = fecDesde;
    }
    public Date getFecHasta() {
        return this.fecHasta;
    }
    
    public void setFecHasta(Date fecHasta) {
        this.fecHasta = fecHasta;
    }
    public String getDesNotas() {
        return this.desNotas;
    }
    
    public void setDesNotas(String desNotas) {
        this.desNotas = desNotas;
    }
    public String getCodTrolesta() {
        return this.codTrolesta;
    }
    
    public void setCodTrolesta(String codTrolesta) {
        this.codTrolesta = codTrolesta;
    }
    public String getCodClaseesta() {
        return this.codClaseesta;
    }
    
    public void setCodClaseesta(String codClaseesta) {
        this.codClaseesta = codClaseesta;
    }
    public String getDesClaseesta() {
        return this.desClaseesta;
    }
    
    public void setDesClaseesta(String desClaseesta) {
        this.desClaseesta = desClaseesta;
    }
    public BigDecimal getIdClaseesta() {
        return this.idClaseesta;
    }
    
    public void setIdClaseesta(BigDecimal idClaseesta) {
        this.idClaseesta = idClaseesta;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ViSicestageneral) ) return false;
		 ViSicestageneral castOther = ( ViSicestageneral ) other; 
         
		 return ( (this.getIdEsta()==castOther.getIdEsta()) || ( this.getIdEsta()!=null && castOther.getIdEsta()!=null && this.getIdEsta().equals(castOther.getIdEsta()) ) )
 && ( (this.getIdTrolesta()==castOther.getIdTrolesta()) || ( this.getIdTrolesta()!=null && castOther.getIdTrolesta()!=null && this.getIdTrolesta().equals(castOther.getIdTrolesta()) ) )
 && ( (this.getDesEsta()==castOther.getDesEsta()) || ( this.getDesEsta()!=null && castOther.getDesEsta()!=null && this.getDesEsta().equals(castOther.getDesEsta()) ) )
 && ( (this.getCodEsta()==castOther.getCodEsta()) || ( this.getCodEsta()!=null && castOther.getCodEsta()!=null && this.getCodEsta().equals(castOther.getCodEsta()) ) )
 && ( (this.getFecDesde()==castOther.getFecDesde()) || ( this.getFecDesde()!=null && castOther.getFecDesde()!=null && this.getFecDesde().equals(castOther.getFecDesde()) ) )
 && ( (this.getFecHasta()==castOther.getFecHasta()) || ( this.getFecHasta()!=null && castOther.getFecHasta()!=null && this.getFecHasta().equals(castOther.getFecHasta()) ) )
 && ( (this.getDesNotas()==castOther.getDesNotas()) || ( this.getDesNotas()!=null && castOther.getDesNotas()!=null && this.getDesNotas().equals(castOther.getDesNotas()) ) )
 && ( (this.getCodTrolesta()==castOther.getCodTrolesta()) || ( this.getCodTrolesta()!=null && castOther.getCodTrolesta()!=null && this.getCodTrolesta().equals(castOther.getCodTrolesta()) ) )
 && ( (this.getCodClaseesta()==castOther.getCodClaseesta()) || ( this.getCodClaseesta()!=null && castOther.getCodClaseesta()!=null && this.getCodClaseesta().equals(castOther.getCodClaseesta()) ) )
 && ( (this.getDesClaseesta()==castOther.getDesClaseesta()) || ( this.getDesClaseesta()!=null && castOther.getDesClaseesta()!=null && this.getDesClaseesta().equals(castOther.getDesClaseesta()) ) )
 && ( (this.getIdClaseesta()==castOther.getIdClaseesta()) || ( this.getIdClaseesta()!=null && castOther.getIdClaseesta()!=null && this.getIdClaseesta().equals(castOther.getIdClaseesta()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdEsta() == null ? 0 : this.getIdEsta().hashCode() );
         result = 37 * result + ( getIdTrolesta() == null ? 0 : this.getIdTrolesta().hashCode() );
         result = 37 * result + ( getDesEsta() == null ? 0 : this.getDesEsta().hashCode() );
         result = 37 * result + ( getCodEsta() == null ? 0 : this.getCodEsta().hashCode() );
         result = 37 * result + ( getFecDesde() == null ? 0 : this.getFecDesde().hashCode() );
         result = 37 * result + ( getFecHasta() == null ? 0 : this.getFecHasta().hashCode() );
         result = 37 * result + ( getDesNotas() == null ? 0 : this.getDesNotas().hashCode() );
         result = 37 * result + ( getCodTrolesta() == null ? 0 : this.getCodTrolesta().hashCode() );
         result = 37 * result + ( getCodClaseesta() == null ? 0 : this.getCodClaseesta().hashCode() );
         result = 37 * result + ( getDesClaseesta() == null ? 0 : this.getDesClaseesta().hashCode() );
         result = 37 * result + ( getIdClaseesta() == null ? 0 : this.getIdClaseesta().hashCode() );
         return result;
   }   



}


