package com.general.hibernate1;
// Generated 31/03/2019 04:18:33 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Sic1docufacturadorsunat generated by hbm2java
 */
public class Sic1docufacturadorsunat  implements java.io.Serializable {

    private Sic1docufacturadorsunatId id;
    private String numRuc;
    private String tipDocu;
    private String numDocu;
    private String fecCarg;
    private String fecGene;
    private String fecEnvi;
    private String desObse;
    private String nomArch;
    private String indSitu;
    private String tipArch;
    private String firmDigital;
    private BigDecimal flgActivo;

    /*AGREGADOR*/
    private String desSitu; //situacion o estado
    private String fecDesde;
    private String fecHasta;

    public Sic1docufacturadorsunat() {
    }

	
    public Sic1docufacturadorsunat(Sic1docufacturadorsunatId id) {
        this.id = id;
    }
    public Sic1docufacturadorsunat(Sic1docufacturadorsunatId id, String numRuc, String tipDocu, String numDocu, String fecCarg, String fecGene, String fecEnvi, String desObse, String nomArch, String indSitu, String tipArch, String firmDigital, BigDecimal flgActivo) {
       this.id = id;
       this.numRuc = numRuc;
       this.tipDocu = tipDocu;
       this.numDocu = numDocu;
       this.fecCarg = fecCarg;
       this.fecGene = fecGene;
       this.fecEnvi = fecEnvi;
       this.desObse = desObse;
       this.nomArch = nomArch;
       this.indSitu = indSitu;
       this.tipArch = tipArch;
       this.firmDigital = firmDigital;
       this.flgActivo = flgActivo;
    }
   
    public Sic1docufacturadorsunatId getId() {
        return this.id;
    }
    
    public void setId(Sic1docufacturadorsunatId id) {
        this.id = id;
    }
    public String getNumRuc() {
        return this.numRuc;
    }
    
    public void setNumRuc(String numRuc) {
        this.numRuc = numRuc;
    }
    public String getTipDocu() {
        return this.tipDocu;
    }
    
    public void setTipDocu(String tipDocu) {
        this.tipDocu = tipDocu;
    }
    public String getNumDocu() {
        return this.numDocu;
    }
    
    public void setNumDocu(String numDocu) {
        this.numDocu = numDocu;
    }

    public String getFecCarg() {
        return fecCarg;
    }

    public void setFecCarg(String fecCarg) {
        this.fecCarg = fecCarg;
    }

    public String getFecGene() {
        return fecGene;
    }

    public void setFecGene(String fecGene) {
        this.fecGene = fecGene;
    }

    public String getFecEnvi() {
        return fecEnvi;
    }

    public void setFecEnvi(String fecEnvi) {
        this.fecEnvi = fecEnvi;
    }   
    
    public String getDesObse() {
        return this.desObse;
    }
    
    public void setDesObse(String desObse) {
        this.desObse = desObse;
    }
    public String getNomArch() {
        return this.nomArch;
    }
    
    public void setNomArch(String nomArch) {
        this.nomArch = nomArch;
    }
    public String getIndSitu() {
        return this.indSitu;
    }
    
    public void setIndSitu(String indSitu) {
        this.indSitu = indSitu;
    }
    public String getTipArch() {
        return this.tipArch;
    }
    
    public void setTipArch(String tipArch) {
        this.tipArch = tipArch;
    }
    public String getFirmDigital() {
        return this.firmDigital;
    }
    
    public void setFirmDigital(String firmDigital) {
        this.firmDigital = firmDigital;
    }
    public BigDecimal getFlgActivo() {
        return this.flgActivo;
    }
    
    public void setFlgActivo(BigDecimal flgActivo) {
        this.flgActivo = flgActivo;
    }

    public String getDesSitu() {
        return desSitu;
    }

    public void setDesSitu(String desSitu) {
        this.desSitu = desSitu;
    }

    public String getFecDesde() {
        return fecDesde;
    }

    public void setFecDesde(String fecDesde) {
        this.fecDesde = fecDesde;
    }

    public String getFecHasta() {
        return fecHasta;
    }

    public void setFecHasta(String fecHasta) {
        this.fecHasta = fecHasta;
    }

    
    
}


