package com.general.hibernate1;
// Generated 11/03/2018 11:19:20 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Sic1docukardexId generated by hbm2java
 */
public class Sic1docukardexId  implements java.io.Serializable {


     private BigDecimal idDocu;
     private BigDecimal numPeri;
     private BigDecimal numItem;
     private BigDecimal idEstab;
     private BigDecimal idProd;

    public Sic1docukardexId() {
    }

    public Sic1docukardexId(BigDecimal idDocu, BigDecimal numPeri, BigDecimal numItem, BigDecimal idEstab, BigDecimal idProd) {
       this.idDocu = idDocu;
       this.numPeri = numPeri;
       this.numItem = numItem;
       this.idEstab = idEstab;
       this.idProd = idProd;
    }
   
    public BigDecimal getIdDocu() {
        return this.idDocu;
    }
    
    public void setIdDocu(BigDecimal idDocu) {
        this.idDocu = idDocu;
    }
    public BigDecimal getNumPeri() {
        return this.numPeri;
    }
    
    public void setNumPeri(BigDecimal numPeri) {
        this.numPeri = numPeri;
    }
    public BigDecimal getNumItem() {
        return this.numItem;
    }
    
    public void setNumItem(BigDecimal numItem) {
        this.numItem = numItem;
    }
    public BigDecimal getIdEstab() {
        return this.idEstab;
    }
    
    public void setIdEstab(BigDecimal idEstab) {
        this.idEstab = idEstab;
    }
    public BigDecimal getIdProd() {
        return this.idProd;
    }
    
    public void setIdProd(BigDecimal idProd) {
        this.idProd = idProd;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Sic1docukardexId) ) return false;
		 Sic1docukardexId castOther = ( Sic1docukardexId ) other; 
         
		 return ( (this.getIdDocu()==castOther.getIdDocu()) || ( this.getIdDocu()!=null && castOther.getIdDocu()!=null && this.getIdDocu().equals(castOther.getIdDocu()) ) )
 && ( (this.getNumPeri()==castOther.getNumPeri()) || ( this.getNumPeri()!=null && castOther.getNumPeri()!=null && this.getNumPeri().equals(castOther.getNumPeri()) ) )
 && ( (this.getNumItem()==castOther.getNumItem()) || ( this.getNumItem()!=null && castOther.getNumItem()!=null && this.getNumItem().equals(castOther.getNumItem()) ) )
 && ( (this.getIdEstab()==castOther.getIdEstab()) || ( this.getIdEstab()!=null && castOther.getIdEstab()!=null && this.getIdEstab().equals(castOther.getIdEstab()) ) )
 && ( (this.getIdProd()==castOther.getIdProd()) || ( this.getIdProd()!=null && castOther.getIdProd()!=null && this.getIdProd().equals(castOther.getIdProd()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdDocu() == null ? 0 : this.getIdDocu().hashCode() );
         result = 37 * result + ( getNumPeri() == null ? 0 : this.getNumPeri().hashCode() );
         result = 37 * result + ( getNumItem() == null ? 0 : this.getNumItem().hashCode() );
         result = 37 * result + ( getIdEstab() == null ? 0 : this.getIdEstab().hashCode() );
         result = 37 * result + ( getIdProd() == null ? 0 : this.getIdProd().hashCode() );
         return result;
   }   


}


