package com.general.hibernate1;
// Generated 04/01/2018 06:43:52 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Sic7estarol generated by hbm2java
 */
public class Sic7estarol  implements java.io.Serializable {


     private Sic7estarolId id;
     private Date fecDesde;
     private Date fecHasta;
     private String desNotas;
     private String desInicio;
     private String desFinal;
     private String desSignifica;

    public Sic7estarol() {
    }

	
    public Sic7estarol(Sic7estarolId id) {
        this.id = id;
    }
    public Sic7estarol(Sic7estarolId id, Date fecDesde, Date fecHasta, String desNotas, String desInicio, String desFinal, String desSignifica) {
       this.id = id;
       this.fecDesde = fecDesde;
       this.fecHasta = fecHasta;
       this.desNotas = desNotas;
       this.desInicio = desInicio;
       this.desFinal = desFinal;
       this.desSignifica = desSignifica;
    }
   
    public Sic7estarolId getId() {
        return this.id;
    }
    
    public void setId(Sic7estarolId id) {
        this.id = id;
    }
    public Date getFecDesde() {
        return this.fecDesde;
    }
    
    public void setFecDesde(Date fecDesde) {
        this.fecDesde = fecDesde;
    }
    public Date getFecHasta() {
        return this.fecHasta;
    }
    
    public void setFecHasta(Date fecHasta) {
        this.fecHasta = fecHasta;
    }
    public String getDesNotas() {
        return this.desNotas;
    }
    
    public void setDesNotas(String desNotas) {
        this.desNotas = desNotas;
    }
    public String getDesInicio() {
        return this.desInicio;
    }
    
    public void setDesInicio(String desInicio) {
        this.desInicio = desInicio;
    }
    public String getDesFinal() {
        return this.desFinal;
    }
    
    public void setDesFinal(String desFinal) {
        this.desFinal = desFinal;
    }
    public String getDesSignifica() {
        return this.desSignifica;
    }
    
    public void setDesSignifica(String desSignifica) {
        this.desSignifica = desSignifica;
    }




}


