package com.general.hibernate1;
// Generated 23/02/2018 02:41:37 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;


/**
 * ViSiccuaddiario generated by hbm2java
 */
public class ViSiccuaddiario  implements java.io.Serializable {

    private BigDecimal idPers;
     private BigDecimal numPeri;
     private String desPers;
     private Date fecApertura;
     private Date fecCierre;
     private String numEfectDenomTotal;
     private String numEfectGastoTotal;
     private String numEfectApertCaja;
     private String numEfectTotalVentaSiste;
     private String numEfectTotalGastoSiste;
     private String numEfectTotalSistema;
     private String numEfectSobraFalta;
     private String numTarjeCrediTotal;
     private String numTarjeDebitTotal;
     private String numTarjeTotal;
     private String numTarjeTotalSiste;
     private String numTarjeSobraFalta;
     private String numTarjeGastoTotal;
     private String numTarjeGastoTotalSiste;
     private String numGastoSobraFalta;
     private BigDecimal idEsta;
     private String codEsta;
     private String desEsta;

    public ViSiccuaddiario() {
    }

	
    public ViSiccuaddiario(BigDecimal idPers, BigDecimal numPeri) {
        this.idPers = idPers;
        this.numPeri = numPeri;
    }
    public ViSiccuaddiario(BigDecimal idPers, BigDecimal numPeri, String desPers, Date fecApertura, Date fecCierre, String numEfectDenomTotal, String numEfectGastoTotal, String numEfectApertCaja, String numEfectTotalVentaSiste, String numEfectTotalGastoSiste, String numEfectTotalSistema, String numEfectSobraFalta, String numTarjeCrediTotal, String numTarjeDebitTotal, String numTarjeTotal, String numTarjeTotalSiste, String numTarjeSobraFalta, String numTarjeGastoTotal, String numTarjeGastoTotalSiste, String numGastoSobraFalta, BigDecimal idEsta, String codEsta, String desEsta) {
       this.idPers = idPers;
       this.numPeri = numPeri;
       this.desPers = desPers;
       this.fecApertura = fecApertura;
       this.fecCierre = fecCierre;
       this.numEfectDenomTotal = numEfectDenomTotal;
       this.numEfectGastoTotal = numEfectGastoTotal;
       this.numEfectApertCaja = numEfectApertCaja;
       this.numEfectTotalVentaSiste = numEfectTotalVentaSiste;
       this.numEfectTotalGastoSiste = numEfectTotalGastoSiste;
       this.numEfectTotalSistema = numEfectTotalSistema;
       this.numEfectSobraFalta = numEfectSobraFalta;
       this.numTarjeCrediTotal = numTarjeCrediTotal;
       this.numTarjeDebitTotal = numTarjeDebitTotal;
       this.numTarjeTotal = numTarjeTotal;
       this.numTarjeTotalSiste = numTarjeTotalSiste;
       this.numTarjeSobraFalta = numTarjeSobraFalta;
       this.numTarjeGastoTotal = numTarjeGastoTotal;
       this.numTarjeGastoTotalSiste = numTarjeGastoTotalSiste;
       this.numGastoSobraFalta = numGastoSobraFalta;
       this.idEsta = idEsta;
       this.codEsta = codEsta;
       this.desEsta = desEsta;
    }
   
    public BigDecimal getIdPers() {
        return this.idPers;
    }
    
    public void setIdPers(BigDecimal idPers) {
        this.idPers = idPers;
    }
    public BigDecimal getNumPeri() {
        return this.numPeri;
    }
    
    public void setNumPeri(BigDecimal numPeri) {
        this.numPeri = numPeri;
    }
    public String getDesPers() {
        return this.desPers;
    }
    
    public void setDesPers(String desPers) {
        this.desPers = desPers;
    }
    public Date getFecApertura() {
        return this.fecApertura;
    }
    
    public void setFecApertura(Date fecApertura) {
        this.fecApertura = fecApertura;
    }
    public Date getFecCierre() {
        return this.fecCierre;
    }
    
    public void setFecCierre(Date fecCierre) {
        this.fecCierre = fecCierre;
    }
    public String getNumEfectDenomTotal() {
        return this.numEfectDenomTotal;
    }
    
    public void setNumEfectDenomTotal(String numEfectDenomTotal) {
        this.numEfectDenomTotal = numEfectDenomTotal;
    }
    public String getNumEfectGastoTotal() {
        return this.numEfectGastoTotal;
    }
    
    public void setNumEfectGastoTotal(String numEfectGastoTotal) {
        this.numEfectGastoTotal = numEfectGastoTotal;
    }
    public String getNumEfectApertCaja() {
        return this.numEfectApertCaja;
    }
    
    public void setNumEfectApertCaja(String numEfectApertCaja) {
        this.numEfectApertCaja = numEfectApertCaja;
    }
    public String getNumEfectTotalVentaSiste() {
        return this.numEfectTotalVentaSiste;
    }
    
    public void setNumEfectTotalVentaSiste(String numEfectTotalVentaSiste) {
        this.numEfectTotalVentaSiste = numEfectTotalVentaSiste;
    }
    public String getNumEfectTotalGastoSiste() {
        return this.numEfectTotalGastoSiste;
    }
    
    public void setNumEfectTotalGastoSiste(String numEfectTotalGastoSiste) {
        this.numEfectTotalGastoSiste = numEfectTotalGastoSiste;
    }
    public String getNumEfectTotalSistema() {
        return this.numEfectTotalSistema;
    }
    
    public void setNumEfectTotalSistema(String numEfectTotalSistema) {
        this.numEfectTotalSistema = numEfectTotalSistema;
    }
    public String getNumEfectSobraFalta() {
        return this.numEfectSobraFalta;
    }
    
    public void setNumEfectSobraFalta(String numEfectSobraFalta) {
        this.numEfectSobraFalta = numEfectSobraFalta;
    }
    public String getNumTarjeCrediTotal() {
        return this.numTarjeCrediTotal;
    }
    
    public void setNumTarjeCrediTotal(String numTarjeCrediTotal) {
        this.numTarjeCrediTotal = numTarjeCrediTotal;
    }
    public String getNumTarjeDebitTotal() {
        return this.numTarjeDebitTotal;
    }
    
    public void setNumTarjeDebitTotal(String numTarjeDebitTotal) {
        this.numTarjeDebitTotal = numTarjeDebitTotal;
    }
    public String getNumTarjeTotal() {
        return this.numTarjeTotal;
    }
    
    public void setNumTarjeTotal(String numTarjeTotal) {
        this.numTarjeTotal = numTarjeTotal;
    }
    public String getNumTarjeTotalSiste() {
        return this.numTarjeTotalSiste;
    }
    
    public void setNumTarjeTotalSiste(String numTarjeTotalSiste) {
        this.numTarjeTotalSiste = numTarjeTotalSiste;
    }
    public String getNumTarjeSobraFalta() {
        return this.numTarjeSobraFalta;
    }
    
    public void setNumTarjeSobraFalta(String numTarjeSobraFalta) {
        this.numTarjeSobraFalta = numTarjeSobraFalta;
    }
    public String getNumTarjeGastoTotal() {
        return this.numTarjeGastoTotal;
    }
    
    public void setNumTarjeGastoTotal(String numTarjeGastoTotal) {
        this.numTarjeGastoTotal = numTarjeGastoTotal;
    }
    public String getNumTarjeGastoTotalSiste() {
        return this.numTarjeGastoTotalSiste;
    }
    
    public void setNumTarjeGastoTotalSiste(String numTarjeGastoTotalSiste) {
        this.numTarjeGastoTotalSiste = numTarjeGastoTotalSiste;
    }
    public String getNumGastoSobraFalta() {
        return this.numGastoSobraFalta;
    }
    
    public void setNumGastoSobraFalta(String numGastoSobraFalta) {
        this.numGastoSobraFalta = numGastoSobraFalta;
    }
    public BigDecimal getIdEsta() {
        return this.idEsta;
    }
    
    public void setIdEsta(BigDecimal idEsta) {
        this.idEsta = idEsta;
    }
    public String getCodEsta() {
        return this.codEsta;
    }
    
    public void setCodEsta(String codEsta) {
        this.codEsta = codEsta;
    }
    public String getDesEsta() {
        return this.desEsta;
    }
    
    public void setDesEsta(String desEsta) {
        this.desEsta = desEsta;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ViSiccuaddiario) ) return false;
		 ViSiccuaddiario castOther = ( ViSiccuaddiario ) other; 
         
		 return ( (this.getIdPers()==castOther.getIdPers()) || ( this.getIdPers()!=null && castOther.getIdPers()!=null && this.getIdPers().equals(castOther.getIdPers()) ) )
 && ( (this.getNumPeri()==castOther.getNumPeri()) || ( this.getNumPeri()!=null && castOther.getNumPeri()!=null && this.getNumPeri().equals(castOther.getNumPeri()) ) )
 && ( (this.getDesPers()==castOther.getDesPers()) || ( this.getDesPers()!=null && castOther.getDesPers()!=null && this.getDesPers().equals(castOther.getDesPers()) ) )
 && ( (this.getFecApertura()==castOther.getFecApertura()) || ( this.getFecApertura()!=null && castOther.getFecApertura()!=null && this.getFecApertura().equals(castOther.getFecApertura()) ) )
 && ( (this.getFecCierre()==castOther.getFecCierre()) || ( this.getFecCierre()!=null && castOther.getFecCierre()!=null && this.getFecCierre().equals(castOther.getFecCierre()) ) )
 && ( (this.getNumEfectDenomTotal()==castOther.getNumEfectDenomTotal()) || ( this.getNumEfectDenomTotal()!=null && castOther.getNumEfectDenomTotal()!=null && this.getNumEfectDenomTotal().equals(castOther.getNumEfectDenomTotal()) ) )
 && ( (this.getNumEfectGastoTotal()==castOther.getNumEfectGastoTotal()) || ( this.getNumEfectGastoTotal()!=null && castOther.getNumEfectGastoTotal()!=null && this.getNumEfectGastoTotal().equals(castOther.getNumEfectGastoTotal()) ) )
 && ( (this.getNumEfectApertCaja()==castOther.getNumEfectApertCaja()) || ( this.getNumEfectApertCaja()!=null && castOther.getNumEfectApertCaja()!=null && this.getNumEfectApertCaja().equals(castOther.getNumEfectApertCaja()) ) )
 && ( (this.getNumEfectTotalVentaSiste()==castOther.getNumEfectTotalVentaSiste()) || ( this.getNumEfectTotalVentaSiste()!=null && castOther.getNumEfectTotalVentaSiste()!=null && this.getNumEfectTotalVentaSiste().equals(castOther.getNumEfectTotalVentaSiste()) ) )
 && ( (this.getNumEfectTotalGastoSiste()==castOther.getNumEfectTotalGastoSiste()) || ( this.getNumEfectTotalGastoSiste()!=null && castOther.getNumEfectTotalGastoSiste()!=null && this.getNumEfectTotalGastoSiste().equals(castOther.getNumEfectTotalGastoSiste()) ) )
 && ( (this.getNumEfectTotalSistema()==castOther.getNumEfectTotalSistema()) || ( this.getNumEfectTotalSistema()!=null && castOther.getNumEfectTotalSistema()!=null && this.getNumEfectTotalSistema().equals(castOther.getNumEfectTotalSistema()) ) )
 && ( (this.getNumEfectSobraFalta()==castOther.getNumEfectSobraFalta()) || ( this.getNumEfectSobraFalta()!=null && castOther.getNumEfectSobraFalta()!=null && this.getNumEfectSobraFalta().equals(castOther.getNumEfectSobraFalta()) ) )
 && ( (this.getNumTarjeCrediTotal()==castOther.getNumTarjeCrediTotal()) || ( this.getNumTarjeCrediTotal()!=null && castOther.getNumTarjeCrediTotal()!=null && this.getNumTarjeCrediTotal().equals(castOther.getNumTarjeCrediTotal()) ) )
 && ( (this.getNumTarjeDebitTotal()==castOther.getNumTarjeDebitTotal()) || ( this.getNumTarjeDebitTotal()!=null && castOther.getNumTarjeDebitTotal()!=null && this.getNumTarjeDebitTotal().equals(castOther.getNumTarjeDebitTotal()) ) )
 && ( (this.getNumTarjeTotal()==castOther.getNumTarjeTotal()) || ( this.getNumTarjeTotal()!=null && castOther.getNumTarjeTotal()!=null && this.getNumTarjeTotal().equals(castOther.getNumTarjeTotal()) ) )
 && ( (this.getNumTarjeTotalSiste()==castOther.getNumTarjeTotalSiste()) || ( this.getNumTarjeTotalSiste()!=null && castOther.getNumTarjeTotalSiste()!=null && this.getNumTarjeTotalSiste().equals(castOther.getNumTarjeTotalSiste()) ) )
 && ( (this.getNumTarjeSobraFalta()==castOther.getNumTarjeSobraFalta()) || ( this.getNumTarjeSobraFalta()!=null && castOther.getNumTarjeSobraFalta()!=null && this.getNumTarjeSobraFalta().equals(castOther.getNumTarjeSobraFalta()) ) )
 && ( (this.getNumTarjeGastoTotal()==castOther.getNumTarjeGastoTotal()) || ( this.getNumTarjeGastoTotal()!=null && castOther.getNumTarjeGastoTotal()!=null && this.getNumTarjeGastoTotal().equals(castOther.getNumTarjeGastoTotal()) ) )
 && ( (this.getNumTarjeGastoTotalSiste()==castOther.getNumTarjeGastoTotalSiste()) || ( this.getNumTarjeGastoTotalSiste()!=null && castOther.getNumTarjeGastoTotalSiste()!=null && this.getNumTarjeGastoTotalSiste().equals(castOther.getNumTarjeGastoTotalSiste()) ) )
 && ( (this.getNumGastoSobraFalta()==castOther.getNumGastoSobraFalta()) || ( this.getNumGastoSobraFalta()!=null && castOther.getNumGastoSobraFalta()!=null && this.getNumGastoSobraFalta().equals(castOther.getNumGastoSobraFalta()) ) )
 && ( (this.getIdEsta()==castOther.getIdEsta()) || ( this.getIdEsta()!=null && castOther.getIdEsta()!=null && this.getIdEsta().equals(castOther.getIdEsta()) ) )
 && ( (this.getCodEsta()==castOther.getCodEsta()) || ( this.getCodEsta()!=null && castOther.getCodEsta()!=null && this.getCodEsta().equals(castOther.getCodEsta()) ) )
 && ( (this.getDesEsta()==castOther.getDesEsta()) || ( this.getDesEsta()!=null && castOther.getDesEsta()!=null && this.getDesEsta().equals(castOther.getDesEsta()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdPers() == null ? 0 : this.getIdPers().hashCode() );
         result = 37 * result + ( getNumPeri() == null ? 0 : this.getNumPeri().hashCode() );
         result = 37 * result + ( getDesPers() == null ? 0 : this.getDesPers().hashCode() );
         result = 37 * result + ( getFecApertura() == null ? 0 : this.getFecApertura().hashCode() );
         result = 37 * result + ( getFecCierre() == null ? 0 : this.getFecCierre().hashCode() );
         result = 37 * result + ( getNumEfectDenomTotal() == null ? 0 : this.getNumEfectDenomTotal().hashCode() );
         result = 37 * result + ( getNumEfectGastoTotal() == null ? 0 : this.getNumEfectGastoTotal().hashCode() );
         result = 37 * result + ( getNumEfectApertCaja() == null ? 0 : this.getNumEfectApertCaja().hashCode() );
         result = 37 * result + ( getNumEfectTotalVentaSiste() == null ? 0 : this.getNumEfectTotalVentaSiste().hashCode() );
         result = 37 * result + ( getNumEfectTotalGastoSiste() == null ? 0 : this.getNumEfectTotalGastoSiste().hashCode() );
         result = 37 * result + ( getNumEfectTotalSistema() == null ? 0 : this.getNumEfectTotalSistema().hashCode() );
         result = 37 * result + ( getNumEfectSobraFalta() == null ? 0 : this.getNumEfectSobraFalta().hashCode() );
         result = 37 * result + ( getNumTarjeCrediTotal() == null ? 0 : this.getNumTarjeCrediTotal().hashCode() );
         result = 37 * result + ( getNumTarjeDebitTotal() == null ? 0 : this.getNumTarjeDebitTotal().hashCode() );
         result = 37 * result + ( getNumTarjeTotal() == null ? 0 : this.getNumTarjeTotal().hashCode() );
         result = 37 * result + ( getNumTarjeTotalSiste() == null ? 0 : this.getNumTarjeTotalSiste().hashCode() );
         result = 37 * result + ( getNumTarjeSobraFalta() == null ? 0 : this.getNumTarjeSobraFalta().hashCode() );
         result = 37 * result + ( getNumTarjeGastoTotal() == null ? 0 : this.getNumTarjeGastoTotal().hashCode() );
         result = 37 * result + ( getNumTarjeGastoTotalSiste() == null ? 0 : this.getNumTarjeGastoTotalSiste().hashCode() );
         result = 37 * result + ( getNumGastoSobraFalta() == null ? 0 : this.getNumGastoSobraFalta().hashCode() );
         result = 37 * result + ( getIdEsta() == null ? 0 : this.getIdEsta().hashCode() );
         result = 37 * result + ( getCodEsta() == null ? 0 : this.getCodEsta().hashCode() );
         result = 37 * result + ( getDesEsta() == null ? 0 : this.getDesEsta().hashCode() );
         return result;
   }   

}


