package com.general.hibernate1;
// Generated 24/02/2018 12:10:06 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * ViSiccuaddiarioId generated by hbm2java
 */
public class ViSiccuaddiarioId  implements java.io.Serializable {


     private BigDecimal idPers;
     private BigDecimal numPeri;
     

    public ViSiccuaddiarioId() {
    }
	
    public ViSiccuaddiarioId(BigDecimal idPers, BigDecimal numPeri) {
        this.idPers = idPers;
        this.numPeri = numPeri;
    }
   
   
    public BigDecimal getIdPers() {
        return this.idPers;
    }
    
    public void setIdPers(BigDecimal idPers) {
        this.idPers = idPers;
    }
    public BigDecimal getNumPeri() {
        return this.numPeri;
    }
    
    public void setNumPeri(BigDecimal numPeri) {
        this.numPeri = numPeri;
    }

}


