CREATE OR REPLACE VIEW VI_SICPROD AS
WITH TMP_CANTIDAD AS (
                    SELECT  RELDOCU.ID_PROD
                           ,PROD.COD_PROD
                           ,SUM(CASE S2.COD_SCLASEEVEN WHEN 'VI_SICSCLASEEVENCOMPRA' /*COMPRA*/ THEN -1 * RELDOCU.NUM_CANTIDAD
                                                       WHEN 'VI_SICSCLASEEVENVENTA' /*VENTA*/ THEN RELDOCU.NUM_CANTIDAD END)  AS NUM_CANTIDAD
                    FROM SIC3DOCUPROD RELDOCU
                    JOIN SIC1PROD PROD ON PROD.ID_PROD = RELDOCU.ID_PROD
                    JOIN SIC1DOCU DOCU ON RELDOCU.ID_DOCU = DOCU.ID_DOCU
                    JOIN SIC1SCLASEEVEN S2 ON S2.ID_SCLASEEVEN = DOCU.ID_SCLASEEVEN
                    WHERE S2.COD_SCLASEEVEN IN ('VI_SICSCLASEEVENCOMPRA','VI_SICSCLASEEVENVENTA')
                    GROUP  BY  RELDOCU.ID_PROD
                               ,PROD.COD_PROD ),

     TMP_DETALLECOSTOS AS (

                   SELECT * FROM (
                       /*@DESCRIPCION: SUBCONSULTA QUE SE UTILIZA PARA OBTENER EL DETALLE DE LOS PRECIOS POR CADA PRODUCTO, DESDE EL MAS ALTO HASTA EL MAS BAJO
                         MUESTRA EL DETALLE DE COSTOS DE CADA PRODUCTO CON SU RESPECTIVO ID DOCU DE LA COMPRA */
                         SELECT  ROW_NUMBER() OVER (PARTITION BY T0.ID_PROD ORDER BY T0.NUM_VALOR DESC) AS FILA
                                ,T0.ID_PROD
                                ,T0.ID_DOCU
                                ,T0.NUM_VALOR
                         FROM SIC3DOCUPROD T0
                         JOIN SIC1DOCU DOCU ON T0.ID_DOCU = DOCU.ID_DOCU
                         JOIN SIC1SCLASEEVEN S2 ON S2.ID_SCLASEEVEN = DOCU.ID_SCLASEEVEN
                         WHERE S2.COD_SCLASEEVEN IN ('VI_SICSCLASEEVENCOMPRA') ) WHERE FILA = 1
                   )

SELECT
        S1.ID_PROD
       ,S2.COD_IDEN
       ,S1.COD_PROD
       ,S1.DES_PROD
       ,S1.DES_PRODCOME
       ,S1.ID_STIPOPROD
       ,V2.COD_STIPOPROD
       ,UPPER(V2.DES_STIPOPROD) AS DES_STIPOPROD
       ,UPPER(V2.COD_VALORGENERALREL) AS COD_TIPOPROD
       ,UPPER(V2.DES_GENERALREL) AS DES_TIPOPROD
       ,S1.FEC_DESDE
       ,S2.FEC_HASTA
       ,ROUND(S1.NUM_PRECIO,2) AS NUM_PRECIO
       ,NVL(TMP_CANT.NUM_CANTIDAD,0) AS NUM_CANTIDAD

       ,TMP_COSTOS.ID_DOCU AS NUM_ULTCOSTO_IDDOCU
       ,TMP_COSTOS.NUM_VALOR AS NUM_ULTCOSTO_VALOR
FROM SIC1PROD S1
INNER JOIN SIC1IDENPROD S2 ON S1.ID_PROD = S2.ID_PROD
JOIN VI_SICSTIPOPROD V2 ON V2.ID_STIPOPROD = S1.ID_STIPOPROD
LEFT JOIN TMP_DETALLECOSTOS TMP_COSTOS ON TMP_COSTOS.ID_PROD = S1.ID_PROD
LEFT JOIN TMP_CANTIDAD TMP_CANT ON TMP_CANT.ID_PROD = S1.ID_PROD
ORDER BY COD_PROD ASC

/////////////////


CREATE OR REPLACE VIEW VI_SICDOCU AS
SELECT     S1.ID_DOCU
          ,S8.COD_IDEN
          ,UPPER(S7.DES_SCLASEEVEN) || ': ' || UPPER(S3.Des_Stipodocu) || ' : ' ||  S8.COD_IDEN AS DES_DOCU
          ,S1.FEC_CREACION

          ,S1.ID_PERS AS ID_PERS_CLIEPROV
          ,UPPER(S4.DES_PERS) AS DES_PERS_CLIEPROV
          ,S1.ID_TROLPERS AS ID_TROLPERS_CLIEPROV
          ,S2.DES_TROL AS DES_TROLPERS_CLIEPROV

          ,S1.ID_STIPODOCU
          ,S3.DES_STIPODOCU
          ,S3.COD_STIPODOCU
          ,S1.COD_SERIE
          ,S1.NUM_DOCU
          ,S1.DES_NOTAS
          ,S1.FEC_DESDE
          ,S1.FEC_HASTA
          ,S1.NUM_SUBTOTAL
          ,S1.NUM_IGV
          ,S1.NUM_SUBTOTAL + S1.NUM_IGV AS NUM_TOTAL
          ,S3.ID_TIPODOCU
          ,S5.DES_TIPODOCU
          ,S5.COD_TIPODOCU

          /*Estado*/
          ,T1.ID_ESTADOCU
          ,T3.COD_ESTA
          ,UPPER(T3.DES_ESTA) AS DES_ESTADOCU
          ,T1.FEC_DESDE AS FEC_DESDEESTA
          ,T1.FEC_HASTA AS FEC_HASTAESTA

          ,S7.ID_PERS AS ID_PERS_CREADOR
          ,UPPER(S7.DES_PERS) AS DES_PERS_CREADOR
          ,/*S6.ID_TROLPERS*/NULL AS ID_TROLPERS_CREADOR
          ,V2.DES_TROLPERS AS DES_TROLPERS_CREADOR

     FROM SIC1DOCU S1
          JOIN SIC1IDENDOCU S8 ON S8.ID_DOCU = S1.ID_DOCU
                                  AND S8.ID_TIPOIDEN = PKG_SICCONSGENERAL. FNC_SICOBTIDGEN ('VI_SICTIPOIDEN', 'DOCUMENTO')
          LEFT JOIN VI_SICTROL S2 ON (S2.ID_TROL = S1.ID_TROLPERS)
          LEFT JOIN SIC1STIPODOCU S3 ON (S3.ID_STIPODOCU = S1.ID_STIPODOCU)
          LEFT JOIN SIC1PERS S4 ON (S4.ID_PERS = S1.ID_PERSEXTERNO)
          LEFT JOIN VI_SICTIPODOCU S5 ON (S5.ID_TIPODOCU = S3.ID_TIPODOCU)
          LEFT JOIN SIC1SCLASEEVEN S7 ON S7.ID_SCLASEEVEN = S1.ID_SCLASEEVEN
          LEFT JOIN SIC3DOCUESTA T1 ON (T1.ID_DOCU = S1.ID_DOCU
                                       AND T1.FEC_HASTA = PKG_SICCONSGENERAL.FNC_SICOBTFECINF)
          LEFT JOIN VI_SICESTA T3 ON (T1.ID_ESTADOCU = T3.ID_ESTA)

          LEFT JOIN SIC3DOCUPERS S6 ON S6.ID_DOCU = S1.ID_DOCU
          LEFT JOIN SIC1PERS S7 ON S7.ID_PERS = S1.ID_PERS
          LEFT JOIN VI_SICTROLPERS V2 ON V2.ID_TROLPERS = S6.ID_TROLPERS

