package com.general.hibernate.relaentity;
// Generated 28/10/2017 06:46:21 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Sic3lugarpersId generated by hbm2java
 */
public class Sic3lugarpersId  implements java.io.Serializable {


     private BigDecimal idLugar;
     private BigDecimal idTrelalugar;
     private BigDecimal idPers;
     private BigDecimal idTrolpers;
     private Date fecDesde;

    public Sic3lugarpersId() {
    }

    public Sic3lugarpersId(BigDecimal idLugar, BigDecimal idTrelalugar, BigDecimal idPers, BigDecimal idTrolpers, Date fecDesde) {
       this.idLugar = idLugar;
       this.idTrelalugar = idTrelalugar;
       this.idPers = idPers;
       this.idTrolpers = idTrolpers;
       this.fecDesde = fecDesde;
    }
   
    public BigDecimal getIdLugar() {
        return this.idLugar;
    }
    
    public void setIdLugar(BigDecimal idLugar) {
        this.idLugar = idLugar;
    }
    public BigDecimal getIdTrelalugar() {
        return this.idTrelalugar;
    }
    
    public void setIdTrelalugar(BigDecimal idTrelalugar) {
        this.idTrelalugar = idTrelalugar;
    }
    public BigDecimal getIdPers() {
        return this.idPers;
    }
    
    public void setIdPers(BigDecimal idPers) {
        this.idPers = idPers;
    }
    public BigDecimal getIdTrolpers() {
        return this.idTrolpers;
    }
    
    public void setIdTrolpers(BigDecimal idTrolpers) {
        this.idTrolpers = idTrolpers;
    }
    public Date getFecDesde() {
        return this.fecDesde;
    }
    
    public void setFecDesde(Date fecDesde) {
        this.fecDesde = fecDesde;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Sic3lugarpersId) ) return false;
		 Sic3lugarpersId castOther = ( Sic3lugarpersId ) other; 
         
		 return ( (this.getIdLugar()==castOther.getIdLugar()) || ( this.getIdLugar()!=null && castOther.getIdLugar()!=null && this.getIdLugar().equals(castOther.getIdLugar()) ) )
 && ( (this.getIdTrelalugar()==castOther.getIdTrelalugar()) || ( this.getIdTrelalugar()!=null && castOther.getIdTrelalugar()!=null && this.getIdTrelalugar().equals(castOther.getIdTrelalugar()) ) )
 && ( (this.getIdPers()==castOther.getIdPers()) || ( this.getIdPers()!=null && castOther.getIdPers()!=null && this.getIdPers().equals(castOther.getIdPers()) ) )
 && ( (this.getIdTrolpers()==castOther.getIdTrolpers()) || ( this.getIdTrolpers()!=null && castOther.getIdTrolpers()!=null && this.getIdTrolpers().equals(castOther.getIdTrolpers()) ) )
 && ( (this.getFecDesde()==castOther.getFecDesde()) || ( this.getFecDesde()!=null && castOther.getFecDesde()!=null && this.getFecDesde().equals(castOther.getFecDesde()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdLugar() == null ? 0 : this.getIdLugar().hashCode() );
         result = 37 * result + ( getIdTrelalugar() == null ? 0 : this.getIdTrelalugar().hashCode() );
         result = 37 * result + ( getIdPers() == null ? 0 : this.getIdPers().hashCode() );
         result = 37 * result + ( getIdTrolpers() == null ? 0 : this.getIdTrolpers().hashCode() );
         result = 37 * result + ( getFecDesde() == null ? 0 : this.getFecDesde().hashCode() );
         return result;
   }   


}


