package com.general.hibernate.relaentity;
// Generated 28/11/2017 03:53:55 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Sic3proddocuId generated by hbm2java
 */
public class Sic3proddocuId  implements java.io.Serializable {


     private BigDecimal idProd;
     private BigDecimal idDocu;
     private BigDecimal idTrelaprod;
     private Date fecDesde;

    public Sic3proddocuId() {
    }

    public Sic3proddocuId(BigDecimal idProd, BigDecimal idDocu, BigDecimal idTrelaprod, Date fecDesde) {
       this.idProd = idProd;
       this.idDocu = idDocu;
       this.idTrelaprod = idTrelaprod;
       this.fecDesde = fecDesde;
    }
   
    public BigDecimal getIdProd() {
        return this.idProd;
    }
    
    public void setIdProd(BigDecimal idProd) {
        this.idProd = idProd;
    }
    public BigDecimal getIdDocu() {
        return this.idDocu;
    }
    
    public void setIdDocu(BigDecimal idDocu) {
        this.idDocu = idDocu;
    }
    public BigDecimal getIdTrelaprod() {
        return this.idTrelaprod;
    }
    
    public void setIdTrelaprod(BigDecimal idTrelaprod) {
        this.idTrelaprod = idTrelaprod;
    }
    public Date getFecDesde() {
        return this.fecDesde;
    }
    
    public void setFecDesde(Date fecDesde) {
        this.fecDesde = fecDesde;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Sic3proddocuId) ) return false;
		 Sic3proddocuId castOther = ( Sic3proddocuId ) other; 
         
		 return ( (this.getIdProd()==castOther.getIdProd()) || ( this.getIdProd()!=null && castOther.getIdProd()!=null && this.getIdProd().equals(castOther.getIdProd()) ) )
 && ( (this.getIdDocu()==castOther.getIdDocu()) || ( this.getIdDocu()!=null && castOther.getIdDocu()!=null && this.getIdDocu().equals(castOther.getIdDocu()) ) )
 && ( (this.getIdTrelaprod()==castOther.getIdTrelaprod()) || ( this.getIdTrelaprod()!=null && castOther.getIdTrelaprod()!=null && this.getIdTrelaprod().equals(castOther.getIdTrelaprod()) ) )
 && ( (this.getFecDesde()==castOther.getFecDesde()) || ( this.getFecDesde()!=null && castOther.getFecDesde()!=null && this.getFecDesde().equals(castOther.getFecDesde()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdProd() == null ? 0 : this.getIdProd().hashCode() );
         result = 37 * result + ( getIdDocu() == null ? 0 : this.getIdDocu().hashCode() );
         result = 37 * result + ( getIdTrelaprod() == null ? 0 : this.getIdTrelaprod().hashCode() );
         result = 37 * result + ( getFecDesde() == null ? 0 : this.getFecDesde().hashCode() );
         return result;
   }   


}


