package com.general.hibernate.relaentity;
// Generated 21/12/2017 04:19:00 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Sic3docudocuId generated by hbm2java
 */
public class Sic3docudocuId  implements java.io.Serializable {


     private BigDecimal idTreladocu;
     private BigDecimal idDocu;
     private BigDecimal idDocurel;
     private Date fecDesde;

    public Sic3docudocuId() {
    }

    public Sic3docudocuId(BigDecimal idTreladocu, BigDecimal idDocu, BigDecimal idDocurel, Date fecDesde) {
       this.idTreladocu = idTreladocu;
       this.idDocu = idDocu;
       this.idDocurel = idDocurel;
       this.fecDesde = fecDesde;
    }
   
    public BigDecimal getIdTreladocu() {
        return this.idTreladocu;
    }
    
    public void setIdTreladocu(BigDecimal idTreladocu) {
        this.idTreladocu = idTreladocu;
    }
    public BigDecimal getIdDocu() {
        return this.idDocu;
    }
    
    public void setIdDocu(BigDecimal idDocu) {
        this.idDocu = idDocu;
    }
    public BigDecimal getIdDocurel() {
        return this.idDocurel;
    }
    
    public void setIdDocurel(BigDecimal idDocurel) {
        this.idDocurel = idDocurel;
    }
    public Date getFecDesde() {
        return this.fecDesde;
    }
    
    public void setFecDesde(Date fecDesde) {
        this.fecDesde = fecDesde;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Sic3docudocuId) ) return false;
		 Sic3docudocuId castOther = ( Sic3docudocuId ) other; 
         
		 return ( (this.getIdTreladocu()==castOther.getIdTreladocu()) || ( this.getIdTreladocu()!=null && castOther.getIdTreladocu()!=null && this.getIdTreladocu().equals(castOther.getIdTreladocu()) ) )
 && ( (this.getIdDocu()==castOther.getIdDocu()) || ( this.getIdDocu()!=null && castOther.getIdDocu()!=null && this.getIdDocu().equals(castOther.getIdDocu()) ) )
 && ( (this.getIdDocurel()==castOther.getIdDocurel()) || ( this.getIdDocurel()!=null && castOther.getIdDocurel()!=null && this.getIdDocurel().equals(castOther.getIdDocurel()) ) )
 && ( (this.getFecDesde()==castOther.getFecDesde()) || ( this.getFecDesde()!=null && castOther.getFecDesde()!=null && this.getFecDesde().equals(castOther.getFecDesde()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdTreladocu() == null ? 0 : this.getIdTreladocu().hashCode() );
         result = 37 * result + ( getIdDocu() == null ? 0 : this.getIdDocu().hashCode() );
         result = 37 * result + ( getIdDocurel() == null ? 0 : this.getIdDocurel().hashCode() );
         result = 37 * result + ( getFecDesde() == null ? 0 : this.getFecDesde().hashCode() );
         return result;
   }   


}


