package com.general.hibernate.relaentity;
// Generated 21/12/2017 05:47:36 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Sic3docuesta generated by hbm2java
 */
public class Sic3docuesta  implements java.io.Serializable {


     private Sic3docuestaId id;
     private Date fecHasta;
     private String desNotas;

    public Sic3docuesta() {
    }

	
    public Sic3docuesta(Sic3docuestaId id) {
        this.id = id;
    }
    public Sic3docuesta(Sic3docuestaId id, Date fecHasta, String desNotas) {
       this.id = id;
       this.fecHasta = fecHasta;
       this.desNotas = desNotas;
    }
   
    public Sic3docuestaId getId() {
        return this.id;
    }
    
    public void setId(Sic3docuestaId id) {
        this.id = id;
    }
    public Date getFecHasta() {
        return this.fecHasta;
    }
    
    public void setFecHasta(Date fecHasta) {
        this.fecHasta = fecHasta;
    }
    public String getDesNotas() {
        return this.desNotas;
    }
    
    public void setDesNotas(String desNotas) {
        this.desNotas = desNotas;
    }




}


