package com.general.hibernate.relaentity;
// Generated 12/01/2018 03:16:12 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Sic3persdocu generated by hbm2java
 */
public class Sic3persdocu  implements java.io.Serializable {


     private Sic3persdocuId id;
     private Date fecHasta;
     private String desNotas;
     private BigDecimal idEven;

    public Sic3persdocu() {
    }

	
    public Sic3persdocu(Sic3persdocuId id) {
        this.id = id;
    }
    public Sic3persdocu(Sic3persdocuId id, Date fecHasta, String desNotas, BigDecimal idEven) {
       this.id = id;
       this.fecHasta = fecHasta;
       this.desNotas = desNotas;
       this.idEven = idEven;
    }
   
    public Sic3persdocuId getId() {
        return this.id;
    }
    
    public void setId(Sic3persdocuId id) {
        this.id = id;
    }
    public Date getFecHasta() {
        return this.fecHasta;
    }
    
    public void setFecHasta(Date fecHasta) {
        this.fecHasta = fecHasta;
    }
    public String getDesNotas() {
        return this.desNotas;
    }
    
    public void setDesNotas(String desNotas) {
        this.desNotas = desNotas;
    }
    public BigDecimal getIdEven() {
        return this.idEven;
    }
    
    public void setIdEven(BigDecimal idEven) {
        this.idEven = idEven;
    }




}


