package com.general.hibernate.relaentity;
// Generated 21/12/2017 05:47:36 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Sic3docuestaId generated by hbm2java
 */
public class Sic3docuestaId  implements java.io.Serializable {


     private BigDecimal idTreladocu;
     private BigDecimal idDocu;
     private BigDecimal idTrolestadocu;
     private BigDecimal idEstadocu;
     private Date fecDesde;

    public Sic3docuestaId() {
    }

    public Sic3docuestaId(BigDecimal idTreladocu, BigDecimal idDocu, BigDecimal idTrolestadocu, BigDecimal idEstadocu, Date fecDesde) {
       this.idTreladocu = idTreladocu;
       this.idDocu = idDocu;
       this.idTrolestadocu = idTrolestadocu;
       this.idEstadocu = idEstadocu;
       this.fecDesde = fecDesde;
    }
   
    public BigDecimal getIdTreladocu() {
        return this.idTreladocu;
    }
    
    public void setIdTreladocu(BigDecimal idTreladocu) {
        this.idTreladocu = idTreladocu;
    }
    public BigDecimal getIdDocu() {
        return this.idDocu;
    }
    
    public void setIdDocu(BigDecimal idDocu) {
        this.idDocu = idDocu;
    }
    public BigDecimal getIdTrolestadocu() {
        return this.idTrolestadocu;
    }
    
    public void setIdTrolestadocu(BigDecimal idTrolestadocu) {
        this.idTrolestadocu = idTrolestadocu;
    }
    public BigDecimal getIdEstadocu() {
        return this.idEstadocu;
    }
    
    public void setIdEstadocu(BigDecimal idEstadocu) {
        this.idEstadocu = idEstadocu;
    }
    public Date getFecDesde() {
        return this.fecDesde;
    }
    
    public void setFecDesde(Date fecDesde) {
        this.fecDesde = fecDesde;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Sic3docuestaId) ) return false;
		 Sic3docuestaId castOther = ( Sic3docuestaId ) other; 
         
		 return ( (this.getIdTreladocu()==castOther.getIdTreladocu()) || ( this.getIdTreladocu()!=null && castOther.getIdTreladocu()!=null && this.getIdTreladocu().equals(castOther.getIdTreladocu()) ) )
 && ( (this.getIdDocu()==castOther.getIdDocu()) || ( this.getIdDocu()!=null && castOther.getIdDocu()!=null && this.getIdDocu().equals(castOther.getIdDocu()) ) )
 && ( (this.getIdTrolestadocu()==castOther.getIdTrolestadocu()) || ( this.getIdTrolestadocu()!=null && castOther.getIdTrolestadocu()!=null && this.getIdTrolestadocu().equals(castOther.getIdTrolestadocu()) ) )
 && ( (this.getIdEstadocu()==castOther.getIdEstadocu()) || ( this.getIdEstadocu()!=null && castOther.getIdEstadocu()!=null && this.getIdEstadocu().equals(castOther.getIdEstadocu()) ) )
 && ( (this.getFecDesde()==castOther.getFecDesde()) || ( this.getFecDesde()!=null && castOther.getFecDesde()!=null && this.getFecDesde().equals(castOther.getFecDesde()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdTreladocu() == null ? 0 : this.getIdTreladocu().hashCode() );
         result = 37 * result + ( getIdDocu() == null ? 0 : this.getIdDocu().hashCode() );
         result = 37 * result + ( getIdTrolestadocu() == null ? 0 : this.getIdTrolestadocu().hashCode() );
         result = 37 * result + ( getIdEstadocu() == null ? 0 : this.getIdEstadocu().hashCode() );
         result = 37 * result + ( getFecDesde() == null ? 0 : this.getFecDesde().hashCode() );
         return result;
   }   


}


