package com.general.hibernate.relaentity;
// Generated 28/11/2017 03:53:55 PM by Hibernate Tools 4.3.1


import com.general.hibernate.entity.Sic1docu;
import com.general.hibernate.entity.Sic1prod;
import java.math.BigDecimal;
import java.util.Date;

/**
 * Sic3proddocu generated by hbm2java
 */
public class Sic3proddocu  implements java.io.Serializable {


     private Sic3proddocuId id;
     private Sic1prod sic1prod;
     private Date fecHasta;
     private String desNotas;
     private BigDecimal numValor;
     private BigDecimal numMtodscto;
     private BigDecimal numCantidad;
     
     /*Agregado*/
     private Integer numIndex;
     private Sic1docu sic1docu;

     
    public Sic3proddocu() {
    }
	
    public Sic3proddocu(Sic3proddocuId id, Sic1prod sic1prod) {
        this.id = id;
        this.sic1prod = sic1prod;
    }
    public Sic3proddocu(Sic3proddocuId id, Sic1prod sic1prod, Date fecHasta, String desNotas, BigDecimal numValor, BigDecimal numMtodscto, BigDecimal numCantidad) {
       this.id = id;
       this.sic1prod = sic1prod;
       this.fecHasta = fecHasta;
       this.desNotas = desNotas;
       this.numValor = numValor;
       this.numMtodscto = numMtodscto;
       this.numCantidad = numCantidad;
    }
   
    public Sic3proddocuId getId() {
        return this.id;
    }
    
    public void setId(Sic3proddocuId id) {
        this.id = id;
    }
    public Sic1prod getSic1prod() {
        return this.sic1prod;
    }
    
    public void setSic1prod(Sic1prod sic1prod) {
        this.sic1prod = sic1prod;
    }
    public Date getFecHasta() {
        return this.fecHasta;
    }
    
    public void setFecHasta(Date fecHasta) {
        this.fecHasta = fecHasta;
    }
    public String getDesNotas() {
        return this.desNotas;
    }
    
    public void setDesNotas(String desNotas) {
        this.desNotas = desNotas;
    }
    public BigDecimal getNumValor() {
        return this.numValor;
    }
    
    public void setNumValor(BigDecimal numValor) {
        this.numValor = numValor;
    }
    public BigDecimal getNumMtodscto() {
        return this.numMtodscto;
    }
    
    public void setNumMtodscto(BigDecimal numMtodscto) {
        this.numMtodscto = numMtodscto;
    }
    public BigDecimal getNumCantidad() {
        return this.numCantidad;
    }
    
    public void setNumCantidad(BigDecimal numCantidad) {
        this.numCantidad = numCantidad;
    }
    
    public Sic1docu getSic1docu() {
        return sic1docu;
    }
    
    public void setSic1docu(Sic1docu sic1docu) {
        this.sic1docu = sic1docu;
    }
    
    public Integer getNumIndex() {
        return numIndex;
    }
    
    public void setNumIndex(Integer numIndex) {
        this.numIndex = numIndex;
    }
}


