package com.general.hibernate.relaentity;
// Generated 28/10/2017 06:46:21 PM by Hibernate Tools 4.3.1


import com.general.hibernate.entity.Sic1lugar;
import com.general.hibernate.entity.Sic1pers;
import com.general.hibernate.entity.Sic1pers;
import com.general.hibernate.entity.Sic8trela;
import java.util.Date;

/**
 * Sic3lugarpers generated by hbm2java
 */
public class Sic3lugarpers  implements java.io.Serializable {


     private Sic3lugarpersId id;
     private Sic1pers sic1pers;
     private Sic1lugar sic1lugar;
     private Sic8trela sic8trela;
     private Date fecHasta;
     private String desNotas;

    public Sic3lugarpers() {
    }

	
    public Sic3lugarpers(Sic3lugarpersId id, Sic1pers sic1pers, Sic1lugar sic1lugar, Sic8trela sic8trela) {
        this.id = id;
        this.sic1pers = sic1pers;
        this.sic1lugar = sic1lugar;
        this.sic8trela = sic8trela;
    }
    public Sic3lugarpers(Sic3lugarpersId id, Sic1pers sic1pers, Sic1lugar sic1lugar, Sic8trela sic8trela, Date fecHasta, String desNotas) {
       this.id = id;
       this.sic1pers = sic1pers;
       this.sic1lugar = sic1lugar;
       this.sic8trela = sic8trela;
       this.fecHasta = fecHasta;
       this.desNotas = desNotas;
    }
   
    public Sic3lugarpersId getId() {
        return this.id;
    }
    
    public void setId(Sic3lugarpersId id) {
        this.id = id;
    }
    public Sic1pers getSic1pers() {
        return this.sic1pers;
    }
    
    public void setSic1pers(Sic1pers sic1pers) {
        this.sic1pers = sic1pers;
    }
    public Sic1lugar getSic1lugar() {
        return this.sic1lugar;
    }
    
    public void setSic1lugar(Sic1lugar sic1lugar) {
        this.sic1lugar = sic1lugar;
    }
    public Sic8trela getSic8trela() {
        return this.sic8trela;
    }
    
    public void setSic8trela(Sic8trela sic8trela) {
        this.sic8trela = sic8trela;
    }
    public Date getFecHasta() {
        return this.fecHasta;
    }
    
    public void setFecHasta(Date fecHasta) {
        this.fecHasta = fecHasta;
    }
    public String getDesNotas() {
        return this.desNotas;
    }
    
    public void setDesNotas(String desNotas) {
        this.desNotas = desNotas;
    }




}


