package com.general.hibernate.relaentity;
// Generated 12/01/2018 03:57:41 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Sic3docupers generated by hbm2java
 */
public class Sic3docupers  implements java.io.Serializable {


     private Sic3docupersId id;
     private Date fecHasta;
     private String desNotas;

    public Sic3docupers() {
    }

	
    public Sic3docupers(Sic3docupersId id) {
        this.id = id;
    }
    public Sic3docupers(Sic3docupersId id, Date fecHasta, String desNotas) {
       this.id = id;
       this.fecHasta = fecHasta;
       this.desNotas = desNotas;
    }
   
    public Sic3docupersId getId() {
        return this.id;
    }
    
    public void setId(Sic3docupersId id) {
        this.id = id;
    }
    public Date getFecHasta() {
        return this.fecHasta;
    }
    
    public void setFecHasta(Date fecHasta) {
        this.fecHasta = fecHasta;
    }
    public String getDesNotas() {
        return this.desNotas;
    }
    
    public void setDesNotas(String desNotas) {
        this.desNotas = desNotas;
    }




}


