package com.general.hibernate.entity;
// Generated 28/10/2017 06:46:21 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Sic1idenpers generated by hbm2java
 */
public class Sic1idenpers  implements java.io.Serializable {


     private Sic1idenpersId id;
     private Date fecDesde;
     private Date fecHasta;
     private Sic1pers sic1pers;
     private BigDecimal idPers;

    public Sic1idenpers() {
    }

	
    public Sic1idenpers(Sic1idenpersId id) {
        this.id = id;
    }
    public Sic1idenpers(Sic1idenpersId id, Date fecDesde, Date fecHasta, BigDecimal idPers, Sic1pers sic1pers) {
       this.id = id;
       this.fecDesde = fecDesde;
       this.fecHasta = fecHasta;
       this.idPers = idPers;
       this.sic1pers = sic1pers;
    }
   
    public Sic1idenpersId getId() {
        return this.id;
    }
    
    public void setId(Sic1idenpersId id) {
        this.id = id;
    }
    public Date getFecDesde() {
        return this.fecDesde;
    }
    
    public void setFecDesde(Date fecDesde) {
        this.fecDesde = fecDesde;
    }
    public Date getFecHasta() {
        return this.fecHasta;
    }
    
    public void setFecHasta(Date fecHasta) {
        this.fecHasta = fecHasta;
    }
    
    public BigDecimal getIdPers() {
        return this.idPers;
    }
    
    public void setIdPers(BigDecimal idPers) {
        this.idPers = idPers;
    }

    /**
     * @return the sic1pers
     */
    public Sic1pers getSic1pers() {
        return sic1pers;
    }

    /**
     * @param sic1pers the sic1pers to set
     */
    public void setSic1pers(Sic1pers sic1pers) {
        this.sic1pers = sic1pers;
    }

    public String toString(){
        return 
               " desPers: " + this.fecDesde +
               " fecHasta: " + this.fecHasta;
    }


}


