package com.general.hibernate.entity;
// Generated 28/10/2017 06:46:21 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Sic1lugar generated by hbm2java
 */
public class Sic1lugar  implements java.io.Serializable {


     private BigDecimal idLugar;
     private String desLugar;
     private BigDecimal idTipolugar;
     private String codCodiauto;
     private String desDireccion;
     private Sic1lugardire sic1lugardireByIdLugar;
     private Set sic3lugarperses = new HashSet(0);
     private Set sic1lugardiresForIdDistrito = new HashSet(0);

    public Sic1lugar() {
    }

	
    public Sic1lugar(BigDecimal idLugar, BigDecimal idTipolugar) {
        this.idLugar = idLugar;
        this.idTipolugar = idTipolugar;
    }
    public Sic1lugar(BigDecimal idLugar, String desLugar, BigDecimal idTipolugar, String codCodiauto, String desDireccion, Sic1lugardire sic1lugardireByIdLugar, Set sic3lugarperses, Set sic1lugardiresForIdDistrito) {
       this.idLugar = idLugar;
       this.desLugar = desLugar;
       this.idTipolugar = idTipolugar;
       this.codCodiauto = codCodiauto;
       this.desDireccion = desDireccion;
       this.sic1lugardireByIdLugar = sic1lugardireByIdLugar;
       this.sic3lugarperses = sic3lugarperses;
       this.sic1lugardiresForIdDistrito = sic1lugardiresForIdDistrito;
    }
   
    public BigDecimal getIdLugar() {
        return this.idLugar;
    }
    
    public void setIdLugar(BigDecimal idLugar) {
        this.idLugar = idLugar;
    }
    public String getDesLugar() {
        return this.desLugar;
    }
    
    public void setDesLugar(String desLugar) {
        this.desLugar = desLugar;
    }
    public BigDecimal getIdTipolugar() {
        return this.idTipolugar;
    }
    
    public void setIdTipolugar(BigDecimal idTipolugar) {
        this.idTipolugar = idTipolugar;
    }
    public String getCodCodiauto() {
        return this.codCodiauto;
    }
    
    public void setCodCodiauto(String codCodiauto) {
        this.codCodiauto = codCodiauto;
    }
    public String getDesDireccion() {
        return this.desDireccion;
    }
    
    public void setDesDireccion(String desDireccion) {
        this.desDireccion = desDireccion;
    }
    public Sic1lugardire getSic1lugardireByIdLugar() {
        return this.sic1lugardireByIdLugar;
    }
    
    public void setSic1lugardireByIdLugar(Sic1lugardire sic1lugardireByIdLugar) {
        this.sic1lugardireByIdLugar = sic1lugardireByIdLugar;
    }
    public Set getSic3lugarperses() {
        return this.sic3lugarperses;
    }
    
    public void setSic3lugarperses(Set sic3lugarperses) {
        this.sic3lugarperses = sic3lugarperses;
    }
    public Set getSic1lugardiresForIdDistrito() {
        return this.sic1lugardiresForIdDistrito;
    }
    
    public void setSic1lugardiresForIdDistrito(Set sic1lugardiresForIdDistrito) {
        this.sic1lugardiresForIdDistrito = sic1lugardiresForIdDistrito;
    }




}


