package com.general.hibernate.entity;
// Generated 28/10/2017 06:46:21 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Sic1idenpersId generated by hbm2java
 */
public class Sic1idenpersId  implements java.io.Serializable {


     private BigDecimal idTipoiden;
     private String codIden;

    public Sic1idenpersId() {
    }

    public Sic1idenpersId(BigDecimal idTipoiden, String codIden) {
       this.idTipoiden = idTipoiden;
       this.codIden = codIden;
    }
   
    public BigDecimal getIdTipoiden() {
        return this.idTipoiden;
    }
    
    public void setIdTipoiden(BigDecimal idTipoiden) {
        this.idTipoiden = idTipoiden;
    }
    public String getCodIden() {
        return this.codIden;
    }
    
    public void setCodIden(String codIden) {
        this.codIden = codIden;
    }




}


