package com.general.hibernate.entity;
// Generated 17/12/2017 10:07:44 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Sic1idendocuId generated by hbm2java
 */
public class Sic1idendocuId  implements java.io.Serializable {


     private String codIden;
     private BigDecimal idTipoiden;

    public Sic1idendocuId() {
    }

    public Sic1idendocuId(String codIden, BigDecimal idTipoiden) {
       this.codIden = codIden;
       this.idTipoiden = idTipoiden;
    }
   
    public String getCodIden() {
        return this.codIden;
    }
    
    public void setCodIden(String codIden) {
        this.codIden = codIden;
    }
    public BigDecimal getIdTipoiden() {
        return this.idTipoiden;
    }
    
    public void setIdTipoiden(BigDecimal idTipoiden) {
        this.idTipoiden = idTipoiden;
    }




}


