package com.general.hibernate.entity;
// Generated 28/10/2017 06:46:21 PM by Hibernate Tools 4.3.1


import com.general.hibernate.entity.Sic1pers;
import java.math.BigDecimal;

/**
 * Sic1persorga generated by hbm2java
 */
public class Sic1persorga  implements java.io.Serializable {


     private BigDecimal idPersorga;
     private Sic1pers sic1pers;
     private String desPersorga;
     private String desNombcome;
     private String desGrupempr;
     private BigDecimal idTipoempr;
     private BigDecimal idTipoorga;

    public Sic1persorga() {
    }

	
    public Sic1persorga(Sic1pers sic1pers) {
        this.sic1pers = sic1pers;
    }
    public Sic1persorga(Sic1pers sic1pers, String desPersorga, String desNombcome, String desGrupempr, BigDecimal idTipoempr, BigDecimal idTipoorga) {
       this.sic1pers = sic1pers;
       this.desPersorga = desPersorga;
       this.desNombcome = desNombcome;
       this.desGrupempr = desGrupempr;
       this.idTipoempr = idTipoempr;
       this.idTipoorga = idTipoorga;
    }
   
    public BigDecimal getIdPersorga() {
        return this.idPersorga;
    }
    
    public void setIdPersorga(BigDecimal idPersorga) {
        this.idPersorga = idPersorga;
    }
    public Sic1pers getSic1pers() {
        return this.sic1pers;
    }
    
    public void setSic1pers(Sic1pers sic1pers) {
        this.sic1pers = sic1pers;
    }
    public String getDesPersorga() {
        return this.desPersorga;
    }
    
    public void setDesPersorga(String desPersorga) {
        this.desPersorga = desPersorga;
    }
    public String getDesNombcome() {
        return this.desNombcome;
    }
    
    public void setDesNombcome(String desNombcome) {
        this.desNombcome = desNombcome;
    }
    public String getDesGrupempr() {
        return this.desGrupempr;
    }
    
    public void setDesGrupempr(String desGrupempr) {
        this.desGrupempr = desGrupempr;
    }
    public BigDecimal getIdTipoempr() {
        return this.idTipoempr;
    }
    
    public void setIdTipoempr(BigDecimal idTipoempr) {
        this.idTipoempr = idTipoempr;
    }
    public BigDecimal getIdTipoorga() {
        return this.idTipoorga;
    }
    
    public void setIdTipoorga(BigDecimal idTipoorga) {
        this.idTipoorga = idTipoorga;
    }

    public String toString(){
        return "idPers: " + this.idPersorga + 
               " desPers: " + this.desPersorga +
               " desCargoRep: " + this.desNombcome +
               " idTipodomi: " + this.idTipoempr +
               " idTipopers: " + this.idTipoempr;               
    }


}


