package com.general.hibernate.entity;
// Generated 19/12/2017 09:58:08 PM by Hibernate Tools 4.3.1


import com.general.hibernate.relaentity.Sic3docuesta;
import com.general.hibernate.relaentity.Sic3docuprod;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * Sic1docu generated by hbm2java
 */
public class Sic1docu  implements java.io.Serializable {


     private BigDecimal idDocu;
     private String desNotas;
     private Date fecCreacion;
     private String desDocu;
     private BigDecimal idTrolpers;
     private BigDecimal idStipodocu;
     private Date fecDesde;
     private Date fecHasta;
     private BigDecimal idPers; //Identificador de quien creó el documento
     private BigDecimal idModapago;
     private BigDecimal idTipotarjeta;
     private BigDecimal numMtotarjeta;
     private BigDecimal numMtocomi;
     private BigDecimal numMtoefectivo;     
     private BigDecimal numMtodscto;
     private BigDecimal numSubtotal;
     private BigDecimal numMtoTotal;
     private BigDecimal numIgv;
     private BigDecimal numMtovuelto;
     private BigDecimal idSclaseeven;
     private BigDecimal idPersexterno; //identificador del Proveedor o Cliente
     
     /*Agregado*/
     private Sic1idendocu sic1idendocu;
     private Sic3docuesta sic3docuesta;
     private List<Sic3docuprod> lstSic3docuprod;
     private String codSerie;
     private BigDecimal numDocu;
     private String codSclaseeven;
     
     private String codEstadocu;

    public Sic1docu() {        
        lstSic3docuprod = new ArrayList<Sic3docuprod>();
    }

	
    public Sic1docu(BigDecimal idDocu) {
        this.idDocu = idDocu;
    }
    public Sic1docu(BigDecimal idDocu, String desNotas, Date fecCreacion, String desDocu, BigDecimal idTrolpers, BigDecimal idStipodocu, Date fecDesde, Date fecHasta, BigDecimal idPers, BigDecimal idModapago, BigDecimal idTipotarjeta, BigDecimal numMtotarjeta, BigDecimal numMtocomi, BigDecimal numMtoefectivo, String codSerie, BigDecimal numDocu, BigDecimal numMtodscto, BigDecimal numSubtotal, BigDecimal numIgv, BigDecimal flgPorrecoger, BigDecimal numMtovuelto ) {
       this.idDocu = idDocu;
       this.desNotas = desNotas;
       this.fecCreacion = fecCreacion;
       this.desDocu = desDocu;
       this.idTrolpers = idTrolpers;
       this.idStipodocu = idStipodocu;
       this.fecDesde = fecDesde;
       this.fecHasta = fecHasta;
       this.idPers = idPers;
       this.idModapago = idModapago;
       this.idTipotarjeta = idTipotarjeta;
       this.numMtotarjeta = numMtotarjeta;
       this.numMtocomi = numMtocomi;
       this.numMtoefectivo = numMtoefectivo;
       this.codSerie = codSerie;
       this.numDocu = numDocu;
       this.numMtodscto = numMtodscto;
       this.numSubtotal = numSubtotal;
       
       this.numIgv = numIgv;       
       this.numMtovuelto = numMtovuelto;
    }
   
    public BigDecimal getIdDocu() {
        return this.idDocu;
    }
    
    public void setIdDocu(BigDecimal idDocu) {
        this.idDocu = idDocu;
    }
    public String getDesNotas() {
        return this.desNotas;
    }
    
    public void setDesNotas(String desNotas) {
        this.desNotas = desNotas;
    }
    public Date getFecCreacion() {
        return this.fecCreacion;
    }
    
    public void setFecCreacion(Date fecCreacion) {
        this.fecCreacion = fecCreacion;
    }
    public String getDesDocu() {
        return this.desDocu;
    }
    
    public void setDesDocu(String desDocu) {
        this.desDocu = desDocu;
    }
    public BigDecimal getIdTrolpers() {
        return this.idTrolpers;
    }
    
    public void setIdTrolpers(BigDecimal idTrolpers) {
        this.idTrolpers = idTrolpers;
    }
    public BigDecimal getIdStipodocu() {
        return this.idStipodocu;
    }
    
    public void setIdStipodocu(BigDecimal idStipodocu) {
        this.idStipodocu = idStipodocu;
    }
    public Date getFecDesde() {
        return this.fecDesde;
    }
    
    public void setFecDesde(Date fecDesde) {
        this.fecDesde = fecDesde;
    }
    public Date getFecHasta() {
        return this.fecHasta;
    }
    
    public void setFecHasta(Date fecHasta) {
        this.fecHasta = fecHasta;
    }
    public BigDecimal getIdPers() {
        return this.idPers;
    }
    
    public void setIdPers(BigDecimal idPers) {
        this.idPers = idPers;
    }
    public BigDecimal getIdModapago() {
        return this.idModapago;
    }
    
    public void setIdModapago(BigDecimal idModapago) {
        this.idModapago = idModapago;
    }
    public BigDecimal getIdTipotarjeta() {
        return this.idTipotarjeta;
    }
    
    public void setIdTipotarjeta(BigDecimal idTipotarjeta) {
        this.idTipotarjeta = idTipotarjeta;
    }
    public BigDecimal getNumMtotarjeta() {
        return this.numMtotarjeta;
    }
    
    public void setNumMtotarjeta(BigDecimal numMtotarjeta) {
        this.numMtotarjeta = numMtotarjeta;
    }
    public BigDecimal getNumMtocomi() {
        return this.numMtocomi;
    }
    
    public void setNumMtocomi(BigDecimal numMtocomi) {
        this.numMtocomi = numMtocomi;
    }
    public BigDecimal getNumMtoefectivo() {
        return this.numMtoefectivo;
    }
    
    public void setNumMtoefectivo(BigDecimal numMtoefectivo) {
        this.numMtoefectivo = numMtoefectivo;
    }
    public String getCodSerie() {
        return this.codSerie;
    }
    
    public void setCodSerie(String codSerie) {
        this.codSerie = codSerie;
    }
    public BigDecimal getNumDocu() {
        return this.numDocu;
    }
    
    public void setNumDocu(BigDecimal numDocu) {
        this.numDocu = numDocu;
    }
    public BigDecimal getNumMtodscto() {
        return this.numMtodscto;
    }
    
    public void setNumMtodscto(BigDecimal numMtodscto) {
        this.numMtodscto = numMtodscto;
    }
    public BigDecimal getNumSubtotal() {
        return this.numSubtotal;
    }
    
    public void setNumSubtotal(BigDecimal numSubtotal) {
        this.numSubtotal = numSubtotal;
    }
    public BigDecimal getNumIgv() {
        return this.numIgv;
    }
    
    public void setNumIgv(BigDecimal numIgv) {
        this.numIgv = numIgv;
    }  

    public BigDecimal getNumMtovuelto() {
        return numMtovuelto;
    }

    public void setNumMtovuelto(BigDecimal numMtovuelto) {
        this.numMtovuelto = numMtovuelto;
    }

    public BigDecimal getIdSclaseeven() {
        return idSclaseeven;
    }

    public void setIdSclaseeven(BigDecimal idSclaseeven) {
        this.idSclaseeven = idSclaseeven;
    }

    public BigDecimal getIdPersexterno() {
        return idPersexterno;
    }

    public void setIdPersexterno(BigDecimal idPersexterno) {
        this.idPersexterno = idPersexterno;
    }

   
    
    

    public List<Sic3docuprod> getLstSic3docuprod() {
        return lstSic3docuprod;
    }

    public void setLstSic3docuprod(List<Sic3docuprod> lstSic3docuprod) {
        this.lstSic3docuprod = lstSic3docuprod;
    }
        
    public Sic1idendocu getSic1idendocu() {
        return sic1idendocu;
    }
  
    public void setSic1idendocu(Sic1idendocu sic1idendocu) {
        this.sic1idendocu = sic1idendocu;
    }
    
    public BigDecimal getNumMtoTotal() {
        return numMtoTotal;
    }
    
    public void setNumMtoTotal(BigDecimal numMtoTotal) {
        this.numMtoTotal = numMtoTotal;
    }
    
    public Sic3docuesta getSic3docuesta() {
        return sic3docuesta;
    }

    public void setSic3docuesta(Sic3docuesta sic3docuesta) {
        this.sic3docuesta = sic3docuesta;
    }   

    public String getCodSclaseeven() {
        return codSclaseeven;
    }

    public void setCodSclaseeven(String codSclaseeven) {
        this.codSclaseeven = codSclaseeven;
    }    
    
    public String getCodEstadocu() {
        return codEstadocu;
    }

    public void setCodEstadocu(String codEstadocu) {
        this.codEstadocu = codEstadocu;
    }
    
    public String toString(){
       return "idDocu: " + this.idDocu + 
              " desDocu: " + this.desDocu +
              " codSerie: " + this.codSerie +
              " numDocu: " + this.numDocu +
              " idPers: " + this.idPers +
              " idStipodocu: " + this.idStipodocu;               
    }
}


