package com.general.hibernate.entity;
// Generated 28/10/2017 06:46:21 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Sic1persindi generated by hbm2java
 */
public class Sic1persindi  implements java.io.Serializable {


     private BigDecimal idPersindi;
     private Sic1pers sic1pers;
     private String desPrimnomb;
     private String desApelmate;
     private String desApelpate;
     private BigDecimal idGenero;
     private String desSegunomb;
     private Date fecNaci;
     

    public Sic1persindi() {
    }

	
    public Sic1persindi(Sic1pers sic1pers) {
        this.sic1pers = sic1pers;
    }
    public Sic1persindi(Sic1pers sic1pers, String desPrimnomb, String desApelmate, String desApelpate, BigDecimal idGenero, String desSegunomb, Date fecNaci) {
       this.sic1pers = sic1pers;
       this.desPrimnomb = desPrimnomb;
       this.desApelmate = desApelmate;
       this.desApelpate = desApelpate;
       this.idGenero = idGenero;
       this.desSegunomb = desSegunomb;
       this.fecNaci = fecNaci;
    }
   
    public BigDecimal getIdPersindi() {
        return this.idPersindi;
    }
    
    public void setIdPersindi(BigDecimal idPersindi) {
        this.idPersindi = idPersindi;
    }
    public Sic1pers getSic1pers() {
        return this.sic1pers;
    }
    
    public void setSic1pers(Sic1pers sic1pers) {
        this.sic1pers = sic1pers;
    }
    public String getDesPrimnomb() {
        return this.desPrimnomb;
    }
    
    public void setDesPrimnomb(String desPrimnomb) {
        this.desPrimnomb = desPrimnomb;
    }
    public String getDesApelmate() {
        return this.desApelmate;
    }
    
    public void setDesApelmate(String desApelmate) {
        this.desApelmate = desApelmate;
    }
    public String getDesApelpate() {
        return this.desApelpate;
    }
    
    public void setDesApelpate(String desApelpate) {
        this.desApelpate = desApelpate;
    }
    public BigDecimal getIdGenero() {
        return this.idGenero;
    }
    
    public void setIdGenero(BigDecimal idGenero) {
        this.idGenero = idGenero;
    }
    public String getDesSegunomb() {
        return this.desSegunomb;
    }
    
    public void setDesSegunomb(String desSegunomb) {
        this.desSegunomb = desSegunomb;
    }
    public Date getFecNaci() {
        return this.fecNaci;
    }
    
    public void setFecNaci(Date fecNaci) {
        this.fecNaci = fecNaci;
    }
    
    
    public String toString(){
        return "idPersindi: " + this.idPersindi + 
               " desPrimnomb: " + this.desPrimnomb +
               " desSegunomb: " + this.desSegunomb +
               " desApelmate: " + this.desApelmate +
               " desApelpate: " + this.desApelpate +
               " fecNaci: " + this.fecNaci + 
                " idGenero: " + this.idGenero;
    }
   
}


