package com.general.hibernate.entity;
// Generated 28/11/2017 03:53:55 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Sic1idenprod generated by hbm2java
 */
public class Sic1idenprod  implements java.io.Serializable {


     private Sic1idenprodId id;
     private Date fecDesde;
     private Date fecHasta;
     private BigDecimal idProd;
     
    

    public Sic1idenprod() {
    }

	
    public Sic1idenprod(Sic1idenprodId id, BigDecimal idProd) {
        this.id = id;
        this.idProd = idProd;
    }
    public Sic1idenprod(Sic1idenprodId id, Date fecDesde, Date fecHasta, BigDecimal idProd) {
       this.id = id;
       this.fecDesde = fecDesde;
       this.fecHasta = fecHasta;
       this.idProd = idProd;
    }
   
    public Sic1idenprodId getId() {
        return this.id;
    }
    
    public void setId(Sic1idenprodId id) {
        this.id = id;
    }
    public Date getFecDesde() {
        return this.fecDesde;
    }
    
    public void setFecDesde(Date fecDesde) {
        this.fecDesde = fecDesde;
    }
    public Date getFecHasta() {
        return this.fecHasta;
    }
    
    public void setFecHasta(Date fecHasta) {
        this.fecHasta = fecHasta;
    }
    public BigDecimal getIdProd() {
        return this.idProd;
    }
    
    public void setIdProd(BigDecimal idProd) {
        this.idProd = idProd;
    }

}


