package com.general.hibernate.entity;
// Generated 21/03/2018 05:22:10 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Sic1sclaseeven generated by hbm2java
 */
public class Sic1sclaseeven  implements java.io.Serializable {


     private BigDecimal idSclaseeven;
     private String desSclaseeven;
     private String codSclaseeven;
     private BigDecimal idClaseeven;
     private String desNotas;

    public Sic1sclaseeven() {
    }

	
    public Sic1sclaseeven(BigDecimal idSclaseeven, String codSclaseeven) {
        this.idSclaseeven = idSclaseeven;
        this.codSclaseeven = codSclaseeven;
    }
    public Sic1sclaseeven(BigDecimal idSclaseeven, String desSclaseeven, String codSclaseeven, BigDecimal idClaseeven, String desNotas) {
       this.idSclaseeven = idSclaseeven;
       this.desSclaseeven = desSclaseeven;
       this.codSclaseeven = codSclaseeven;
       this.idClaseeven = idClaseeven;
       this.desNotas = desNotas;
    }
   
    public BigDecimal getIdSclaseeven() {
        return this.idSclaseeven;
    }
    
    public void setIdSclaseeven(BigDecimal idSclaseeven) {
        this.idSclaseeven = idSclaseeven;
    }
    public String getDesSclaseeven() {
        return this.desSclaseeven;
    }
    
    public void setDesSclaseeven(String desSclaseeven) {
        this.desSclaseeven = desSclaseeven;
    }
    public String getCodSclaseeven() {
        return this.codSclaseeven;
    }
    
    public void setCodSclaseeven(String codSclaseeven) {
        this.codSclaseeven = codSclaseeven;
    }
    public BigDecimal getIdClaseeven() {
        return this.idClaseeven;
    }
    
    public void setIdClaseeven(BigDecimal idClaseeven) {
        this.idClaseeven = idClaseeven;
    }
    public String getDesNotas() {
        return this.desNotas;
    }
    
    public void setDesNotas(String desNotas) {
        this.desNotas = desNotas;
    }




}


