package com.general.hibernate.entity;
// Generated 11/03/2018 11:19:20 AM by Hibernate Tools 4.3.1


import com.general.hibernate.entity.Sic1prod;
import java.math.BigDecimal;
import java.util.Date;

/**
 * Sic1docukardex generated by hbm2java
 */
public class Sic1docukardex  implements java.io.Serializable {


     private Sic1docukardexId id;
     private Date fecCreacion;
     private BigDecimal numCantini;
     private BigDecimal numCantingr;
     private BigDecimal numCantsali;
     private BigDecimal numCantstock;     
     
     /*Agregado*/
     private Sic1prod sic1prod;
     private BigDecimal numCantstockusu;

    public Sic1docukardex() {
    }

	
    public Sic1docukardex(Sic1docukardexId id) {
        this.id = id;
    }
    public Sic1docukardex(Sic1docukardexId id, Date fecCreacion, BigDecimal numCantini, BigDecimal numCantingr, BigDecimal numCantsali, BigDecimal numCantstock) {
       this.id = id;
       this.fecCreacion = fecCreacion;
       this.numCantini = numCantini;
       this.numCantingr = numCantingr;
       this.numCantsali = numCantsali;
       this.numCantstock = numCantstock;
    }
   
    public Sic1docukardexId getId() {
        return this.id;
    }
    
    public void setId(Sic1docukardexId id) {
        this.id = id;
    }
    public Date getFecCreacion() {
        return this.fecCreacion;
    }
    
    public void setFecCreacion(Date fecCreacion) {
        this.fecCreacion = fecCreacion;
    }
    public BigDecimal getNumCantini() {
        return this.numCantini;
    }
    
    public void setNumCantini(BigDecimal numCantini) {
        this.numCantini = numCantini;
    }
    public BigDecimal getNumCantingr() {
        return this.numCantingr;
    }
    
    public void setNumCantingr(BigDecimal numCantingr) {
        this.numCantingr = numCantingr;
    }
    public BigDecimal getNumCantsali() {
        return this.numCantsali;
    }
    
    public void setNumCantsali(BigDecimal numCantsali) {
        this.numCantsali = numCantsali;
    }
    public BigDecimal getNumCantstock() {
        return this.numCantstock;
    }
    
    public void setNumCantstock(BigDecimal numCantstock) {
        this.numCantstock = numCantstock;
    }

    public Sic1prod getSic1prod() {
        return sic1prod;
    }

    public void setSic1prod(Sic1prod sic1prod) {
        this.sic1prod = sic1prod;
    }
    
    public BigDecimal getNumCantstockusu() {
        return numCantstockusu;
    }

    public void setNumCantstockusu(BigDecimal numCantstockusu) {
        this.numCantstockusu = numCantstockusu;
    }
}


