package com.general.hibernate.entity;
// Generated 28/11/2017 03:53:55 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Sic1idenprodId generated by hbm2java
 */
public class Sic1idenprodId  implements java.io.Serializable {


     private BigDecimal idTipoiden;
     private String codIden;

    public Sic1idenprodId() {
    }

    public Sic1idenprodId(BigDecimal idTipoiden, String codIden) {
       this.idTipoiden = idTipoiden;
       this.codIden = codIden;
    }
   
    public BigDecimal getIdTipoiden() {
        return this.idTipoiden;
    }
    
    public void setIdTipoiden(BigDecimal idTipoiden) {
        this.idTipoiden = idTipoiden;
    }
    public String getCodIden() {
        return this.codIden;
    }
    
    public void setCodIden(String codIden) {
        this.codIden = codIden;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Sic1idenprodId) ) return false;
		 Sic1idenprodId castOther = ( Sic1idenprodId ) other; 
         
		 return ( (this.getIdTipoiden()==castOther.getIdTipoiden()) || ( this.getIdTipoiden()!=null && castOther.getIdTipoiden()!=null && this.getIdTipoiden().equals(castOther.getIdTipoiden()) ) )
 && ( (this.getCodIden()==castOther.getCodIden()) || ( this.getCodIden()!=null && castOther.getCodIden()!=null && this.getCodIden().equals(castOther.getCodIden()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdTipoiden() == null ? 0 : this.getIdTipoiden().hashCode() );
         result = 37 * result + ( getCodIden() == null ? 0 : this.getCodIden().hashCode() );
         return result;
   }   


}


