package com.general.hibernate.entity;
// Generated 28/10/2017 06:46:21 PM by Hibernate Tools 4.3.1


import com.general.hibernate.entity.Sic1general;
import java.math.BigDecimal;

/**
 * Sic1lugardire generated by hbm2java
 */
public class Sic1lugardire  implements java.io.Serializable {


     private BigDecimal idLugardire;
     private Sic1lugar sic1lugarByIdLugar;
     private Sic1lugar sic1lugarByIdDistrito;
     private Sic1general sic1generalByIdTipozona;
     private Sic1general sic1generalByIdTipovia;
     private String numLatitud;
     private String numLongitud;
     private BigDecimal numAltitud;
     private String desVia;
     private String desZona;
     private String numDire;
     private String numInterior;
     private String codNumdire;
     private String codNuminterior;

    public Sic1lugardire() {
    }

	
    public Sic1lugardire(Sic1lugar sic1lugarByIdLugar, String desVia, String desZona, String numDire) {
        this.sic1lugarByIdLugar = sic1lugarByIdLugar;
        this.desVia = desVia;
        this.desZona = desZona;
        this.numDire = numDire;
    }
    public Sic1lugardire(Sic1lugar sic1lugarByIdLugar, Sic1lugar sic1lugarByIdDistrito, Sic1general sic1generalByIdTipozona, Sic1general sic1generalByIdTipovia, String numLatitud, String numLongitud, BigDecimal numAltitud, String desVia, String desZona, String numDire, String numInterior, String codNumdire, String codNuminterior) {
       this.sic1lugarByIdLugar = sic1lugarByIdLugar;
       this.sic1lugarByIdDistrito = sic1lugarByIdDistrito;
       this.sic1generalByIdTipozona = sic1generalByIdTipozona;
       this.sic1generalByIdTipovia = sic1generalByIdTipovia;
       this.numLatitud = numLatitud;
       this.numLongitud = numLongitud;
       this.numAltitud = numAltitud;
       this.desVia = desVia;
       this.desZona = desZona;
       this.numDire = numDire;
       this.numInterior = numInterior;
       this.codNumdire = codNumdire;
       this.codNuminterior = codNuminterior;
    }
   
    public BigDecimal getIdLugardire() {
        return this.idLugardire;
    }
    
    public void setIdLugardire(BigDecimal idLugardire) {
        this.idLugardire = idLugardire;
    }
    public Sic1lugar getSic1lugarByIdLugar() {
        return this.sic1lugarByIdLugar;
    }
    
    public void setSic1lugarByIdLugar(Sic1lugar sic1lugarByIdLugar) {
        this.sic1lugarByIdLugar = sic1lugarByIdLugar;
    }
    public Sic1lugar getSic1lugarByIdDistrito() {
        return this.sic1lugarByIdDistrito;
    }
    
    public void setSic1lugarByIdDistrito(Sic1lugar sic1lugarByIdDistrito) {
        this.sic1lugarByIdDistrito = sic1lugarByIdDistrito;
    }
    public Sic1general getSic1generalByIdTipozona() {
        return this.sic1generalByIdTipozona;
    }
    
    public void setSic1generalByIdTipozona(Sic1general sic1generalByIdTipozona) {
        this.sic1generalByIdTipozona = sic1generalByIdTipozona;
    }
    public Sic1general getSic1generalByIdTipovia() {
        return this.sic1generalByIdTipovia;
    }
    
    public void setSic1generalByIdTipovia(Sic1general sic1generalByIdTipovia) {
        this.sic1generalByIdTipovia = sic1generalByIdTipovia;
    }
    public String getNumLatitud() {
        return this.numLatitud;
    }
    
    public void setNumLatitud(String numLatitud) {
        this.numLatitud = numLatitud;
    }
    public String getNumLongitud() {
        return this.numLongitud;
    }
    
    public void setNumLongitud(String numLongitud) {
        this.numLongitud = numLongitud;
    }
    public BigDecimal getNumAltitud() {
        return this.numAltitud;
    }
    
    public void setNumAltitud(BigDecimal numAltitud) {
        this.numAltitud = numAltitud;
    }
    public String getDesVia() {
        return this.desVia;
    }
    
    public void setDesVia(String desVia) {
        this.desVia = desVia;
    }
    public String getDesZona() {
        return this.desZona;
    }
    
    public void setDesZona(String desZona) {
        this.desZona = desZona;
    }
    public String getNumDire() {
        return this.numDire;
    }
    
    public void setNumDire(String numDire) {
        this.numDire = numDire;
    }
    public String getNumInterior() {
        return this.numInterior;
    }
    
    public void setNumInterior(String numInterior) {
        this.numInterior = numInterior;
    }
    public String getCodNumdire() {
        return this.codNumdire;
    }
    
    public void setCodNumdire(String codNumdire) {
        this.codNumdire = codNumdire;
    }
    public String getCodNuminterior() {
        return this.codNuminterior;
    }
    
    public void setCodNuminterior(String codNuminterior) {
        this.codNuminterior = codNuminterior;
    }




}


