package com.general.hibernate.entity;
// Generated 19/12/2017 10:13:13 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Sic1stipodocu generated by hbm2java
 */
public class Sic1stipodocu  implements java.io.Serializable {


     private BigDecimal idStipodocu;
     private String desStipodocu;
     private String codStipodocu;
     private BigDecimal idTipodocu;
     private BigDecimal flgVigencia;
     private BigDecimal idTrolesta;
     private String codPrefcpe;
     private String codSunat;

    public Sic1stipodocu() {
    }

	
    public Sic1stipodocu(BigDecimal idStipodocu, String codStipodocu) {
        this.idStipodocu = idStipodocu;
        this.codStipodocu = codStipodocu;
    }
    public Sic1stipodocu(BigDecimal idStipodocu, String desStipodocu, String codStipodocu, BigDecimal idTipodocu, BigDecimal flgVigencia, BigDecimal idTrolesta) {
       this.idStipodocu = idStipodocu;
       this.desStipodocu = desStipodocu;
       this.codStipodocu = codStipodocu;
       this.idTipodocu = idTipodocu;
       this.flgVigencia = flgVigencia;
       this.idTrolesta = idTrolesta;
    }
   
    public BigDecimal getIdStipodocu() {
        return this.idStipodocu;
    }
    
    public void setIdStipodocu(BigDecimal idStipodocu) {
        this.idStipodocu = idStipodocu;
    }
    public String getDesStipodocu() {
        return this.desStipodocu;
    }
    
    public void setDesStipodocu(String desStipodocu) {
        this.desStipodocu = desStipodocu;
    }
    public String getCodStipodocu() {
        return this.codStipodocu;
    }
    
    public void setCodStipodocu(String codStipodocu) {
        this.codStipodocu = codStipodocu;
    }
    public BigDecimal getIdTipodocu() {
        return this.idTipodocu;
    }
    
    public void setIdTipodocu(BigDecimal idTipodocu) {
        this.idTipodocu = idTipodocu;
    }
    public BigDecimal getFlgVigencia() {
        return this.flgVigencia;
    }
    
    public void setFlgVigencia(BigDecimal flgVigencia) {
        this.flgVigencia = flgVigencia;
    }
    public BigDecimal getIdTrolesta() {
        return this.idTrolesta;
    }
    
    public void setIdTrolesta(BigDecimal idTrolesta) {
        this.idTrolesta = idTrolesta;
    }
    
    public String getCodPrefcpe() {
        return codPrefcpe;
    }

    public void setCodPrefcpe(String codPrefcpe) {
        this.codPrefcpe = codPrefcpe;
    }

    public String getCodSunat() {
        return codSunat;
    }

    public void setCodSunat(String codSunat) {
        this.codSunat = codSunat;
    }   
    
}


