package com.general.hibernate.entity;
// Generated 28/10/2017 06:46:21 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Sic1general generated by hbm2java
 */
public class Sic1general  implements java.io.Serializable {


     private BigDecimal idGeneral;
     private String desGeneral;
     private String codValortipogeneral;
     private String codValorgeneral;
     private BigDecimal idGeneralrel;
     private BigDecimal codValordefecto;
     private String codValortipoentidad;
     private BigDecimal idGeneralrelsec;
     private BigDecimal numValor;
     private String desValor;
     private Date fecValor;
     private String desValor1;
     private Set sic1docus = new HashSet(0);

    public Sic1general() {
    }

	
    public Sic1general(BigDecimal idGeneral) {
        this.idGeneral = idGeneral;
    }
    public Sic1general(BigDecimal idGeneral, String desGeneral, String codValortipogeneral, String codValorgeneral, BigDecimal idGeneralrel, BigDecimal codValordefecto, String codValortipoentidad, BigDecimal idGeneralrelsec, BigDecimal numValor, String desValor, Date fecValor, String desValor1, Set sic1docus) {
       this.idGeneral = idGeneral;
       this.desGeneral = desGeneral;
       this.codValortipogeneral = codValortipogeneral;
       this.codValorgeneral = codValorgeneral;
       this.idGeneralrel = idGeneralrel;
       this.codValordefecto = codValordefecto;
       this.codValortipoentidad = codValortipoentidad;
       this.idGeneralrelsec = idGeneralrelsec;
       this.numValor = numValor;
       this.desValor = desValor;
       this.fecValor = fecValor;
       this.desValor1 = desValor1;
       this.sic1docus = sic1docus;
    }
   
    public BigDecimal getIdGeneral() {
        return this.idGeneral;
    }
    
    public void setIdGeneral(BigDecimal idGeneral) {
        this.idGeneral = idGeneral;
    }
    public String getDesGeneral() {
        return this.desGeneral;
    }
    
    public void setDesGeneral(String desGeneral) {
        this.desGeneral = desGeneral;
    }
    public String getCodValortipogeneral() {
        return this.codValortipogeneral;
    }
    
    public void setCodValortipogeneral(String codValortipogeneral) {
        this.codValortipogeneral = codValortipogeneral;
    }
    public String getCodValorgeneral() {
        return this.codValorgeneral;
    }
    
    public void setCodValorgeneral(String codValorgeneral) {
        this.codValorgeneral = codValorgeneral;
    }
    public BigDecimal getIdGeneralrel() {
        return this.idGeneralrel;
    }
    
    public void setIdGeneralrel(BigDecimal idGeneralrel) {
        this.idGeneralrel = idGeneralrel;
    }
    public BigDecimal getCodValordefecto() {
        return this.codValordefecto;
    }
    
    public void setCodValordefecto(BigDecimal codValordefecto) {
        this.codValordefecto = codValordefecto;
    }
    public String getCodValortipoentidad() {
        return this.codValortipoentidad;
    }
    
    public void setCodValortipoentidad(String codValortipoentidad) {
        this.codValortipoentidad = codValortipoentidad;
    }
    public BigDecimal getIdGeneralrelsec() {
        return this.idGeneralrelsec;
    }
    
    public void setIdGeneralrelsec(BigDecimal idGeneralrelsec) {
        this.idGeneralrelsec = idGeneralrelsec;
    }
    public BigDecimal getNumValor() {
        return this.numValor;
    }
    
    public void setNumValor(BigDecimal numValor) {
        this.numValor = numValor;
    }
    public String getDesValor() {
        return this.desValor;
    }
    
    public void setDesValor(String desValor) {
        this.desValor = desValor;
    }
    public Date getFecValor() {
        return this.fecValor;
    }
    
    public void setFecValor(Date fecValor) {
        this.fecValor = fecValor;
    }
    public String getDesValor1() {
        return this.desValor1;
    }
    
    public void setDesValor1(String desValor1) {
        this.desValor1 = desValor1;
    }
    public Set getSic1docus() {
        return this.sic1docus;
    }
    
    public void setSic1docus(Set sic1docus) {
        this.sic1docus = sic1docus;
    }




}


