package com.general.hibernate.entity;
// Generated 17/12/2017 10:07:44 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Sic1idendocu generated by hbm2java
 */
public class Sic1idendocu  implements java.io.Serializable {


     private Sic1idendocuId id;
     private Date fecDesde;
     private Date fecHasta;
     private BigDecimal idDocu;
     
     /*Agregado*/
     private Sic1docu sic1docu;
     private String codIden;
     private BigDecimal idTipoiden;

    public Sic1idendocu() {
    }

	
    public Sic1idendocu(Sic1idendocuId id, BigDecimal idDocu) {
        this.id = id;
        this.idDocu = idDocu;
    }
    public Sic1idendocu(Sic1idendocuId id, Date fecDesde, Date fecHasta, BigDecimal idDocu) {
       this.id = id;
       this.fecDesde = fecDesde;
       this.fecHasta = fecHasta;
       this.idDocu = idDocu;
    }
   
    public Sic1idendocuId getId() {
        return this.id;
    }
    
    public void setId(Sic1idendocuId id) {
        this.id = id;
    }
    public Date getFecDesde() {
        return this.fecDesde;
    }
    
    public void setFecDesde(Date fecDesde) {
        this.fecDesde = fecDesde;
    }
    public Date getFecHasta() {
        return this.fecHasta;
    }
    
    public void setFecHasta(Date fecHasta) {
        this.fecHasta = fecHasta;
    }
    public BigDecimal getIdDocu() {
        return this.idDocu;
    }
    
    public void setIdDocu(BigDecimal idDocu) {
        this.idDocu = idDocu;
    }

    public String getCodIden() {
        return codIden;
    }

    public void setCodIden(String codIden) {
        this.codIden = codIden;
    }

    public BigDecimal getIdTipoiden() {
        return idTipoiden;
    }

    public void setIdTipoiden(BigDecimal idTipoiden) {
        this.idTipoiden = idTipoiden;
    }

    public Sic1docu getSic1docu() {
        return sic1docu;
    }

    public void setSic1docu(Sic1docu sic1docu) {
        this.sic1docu = sic1docu;
    }

    


}


