package com.general.hibernate.entity;
// Generated 19/12/2017 09:58:08 PM by Hibernate Tools 4.3.1

import com.general.hibernate.relaentity.Sic3docudocu;
import com.general.hibernate.relaentity.Sic3docuesta;
import com.general.hibernate.relaentity.Sic3docupers;
import com.general.hibernate.relaentity.Sic3docuprod;
import com.general.hibernate1.Sic1docufacturadorsunat;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * Sic1docu generated by hbm2java
 */
public class Sic1docu  implements java.io.Serializable {

     private BigDecimal idDocu;
     private String desNotas;
     private Date fecCreacion;
     private String desDocu;
     private BigDecimal idTrolpers;
     private BigDecimal idStipodocu;
     private Date fecDesde;
     private Date fecHasta;
     private BigDecimal idPers; //Identificador de quien creó el documento
     private BigDecimal idModapago;
     private BigDecimal idTipotarjeta;
     private BigDecimal numMtotarjeta;
     private BigDecimal numMtocomi; //Indica la comsion para VISANET
     private BigDecimal numMtoefectivo;
     private BigDecimal numMtodscto;
     private BigDecimal numSubtotal;
     private BigDecimal numMtoTotal;
     private BigDecimal numIgv;
     private BigDecimal numMtovuelto;
     private BigDecimal idSclaseeven;
     private BigDecimal idPersexterno; //identificador del Proveedor o Cliente     
     
     private Integer flgPrecsinIGV;
     private Integer idSucursal;
     private String numVoucher;
     private Integer flgDeclaradosunat;
     
     /*Agregado*/
     private Sic1idendocu sic1idendocu;
     private Sic3docuesta sic3docuesta;
     private Sic3docudocu sic3docudocu;
     private Sic1stipodocu sic1stipodocu;
     private Sic1sclaseeven sic1sclaseeven;
     private Sic1lugar sic1lSucursal;
     private Sic1pers sic1perscontribuyente; //Datos del Contribuyente, es decir de la empresa que emite la factura (INVERSIONES EMZA)
     private Sic1pers sic1persexterno;     //Proveedor O Cliente
     private Sic1pers sic1persregistrador; //Persona que realizo el registro en el sistema
     
     private Sic1docufacturadorsunat sic1docufacturadorsunat;
     private List<Sic3docuprod> lstSic3docuprod;
     private List<Sic3docudocu> lstDocusPadre;
     private List<Sic3docudocu> lstDocusHijo;
     private List<Sic3docupers> lstPersRela;          
     
     private String codSerie;
     private BigDecimal numDocu;
     private String numDocuunido;
     private String codEstadocu;
     private String desEstadocu;     
     private BigDecimal numMtocomitarjeta; //Se guarda la comision segun la configuracion (actual 4% o 5%)
     private Double numMtoPagadoTarjeta;
     private Double numMtoPagadoEfectivo;
     private Double numMtoPagadoComiTarjeta;     
     private String codTrolpersexterno;
     
     private Sic1general objFormaPago;
     private Sic1general objTipoTarjeta;
     private Sic1general objTipoNotaCredDebi;
     

    public Sic1docu() {        
        this.lstSic3docuprod    = new ArrayList<>();
        this.lstDocusPadre      = new ArrayList<>();
        this.lstDocusHijo       = new ArrayList<>();
    }

	
    public Sic1docu(BigDecimal idDocu) {
        this.idDocu = idDocu;
    }
    public Sic1docu(BigDecimal idDocu, String desNotas, Date fecCreacion, String desDocu, BigDecimal idTrolpers, BigDecimal idStipodocu, Date fecDesde, Date fecHasta, BigDecimal idPers, BigDecimal idModapago, BigDecimal idTipotarjeta, BigDecimal numMtotarjeta, BigDecimal numMtocomi, BigDecimal numMtoefectivo, String codSerie, BigDecimal numDocu, BigDecimal numMtodscto, BigDecimal numSubtotal, BigDecimal numIgv, BigDecimal flgPorrecoger, BigDecimal numMtovuelto ) {
       this.idDocu = idDocu;
       this.desNotas = desNotas;
       this.fecCreacion = fecCreacion;
       this.desDocu = desDocu;
       this.idTrolpers = idTrolpers;
       this.idStipodocu = idStipodocu;
       this.fecDesde = fecDesde;
       this.fecHasta = fecHasta;
       this.idPers = idPers;
       this.idModapago = idModapago;
       this.idTipotarjeta = idTipotarjeta;
       this.numMtotarjeta = numMtotarjeta;
       this.numMtocomi = numMtocomi;
       this.numMtoefectivo = numMtoefectivo;
       this.codSerie = codSerie;
       this.numDocu = numDocu;
       this.numMtodscto = numMtodscto;
       this.numSubtotal = numSubtotal;
       
       this.numIgv = numIgv;       
       this.numMtovuelto = numMtovuelto;
    }
   
    public BigDecimal getIdDocu() {
        return this.idDocu;
    }
    
    public void setIdDocu(BigDecimal idDocu) {
        this.idDocu = idDocu;
    }
    public String getDesNotas() {
        return this.desNotas;
    }
    
    public void setDesNotas(String desNotas) {
        this.desNotas = desNotas;
    }
    public Date getFecCreacion() {
        return this.fecCreacion;
    }
    
    public void setFecCreacion(Date fecCreacion) {
        this.fecCreacion = fecCreacion;
    }
    public String getDesDocu() {
        return this.desDocu;
    }
    
    public void setDesDocu(String desDocu) {
        this.desDocu = desDocu;
    }
    public BigDecimal getIdTrolpers() {
        return this.idTrolpers;
    }
    
    public void setIdTrolpers(BigDecimal idTrolpers) {
        this.idTrolpers = idTrolpers;
    }
    public BigDecimal getIdStipodocu() {
        return this.idStipodocu;
    }
    
    public void setIdStipodocu(BigDecimal idStipodocu) {
        this.idStipodocu = idStipodocu;
    }
    public Date getFecDesde() {
        return this.fecDesde;
    }
    
    public void setFecDesde(Date fecDesde) {
        this.fecDesde = fecDesde;
    }
    public Date getFecHasta() {
        return this.fecHasta;
    }
    
    public void setFecHasta(Date fecHasta) {
        this.fecHasta = fecHasta;
    }
    public BigDecimal getIdPers() {
        return this.idPers;
    }
    
    public void setIdPers(BigDecimal idPers) {
        this.idPers = idPers;
    }
    public BigDecimal getIdModapago() {
        return this.idModapago;
    }
    
    public void setIdModapago(BigDecimal idModapago) {
        this.idModapago = idModapago;
    }
    public BigDecimal getIdTipotarjeta() {
        return this.idTipotarjeta;
    }
    
    public void setIdTipotarjeta(BigDecimal idTipotarjeta) {
        this.idTipotarjeta = idTipotarjeta;
    }
    public BigDecimal getNumMtotarjeta() {
        return this.numMtotarjeta;
    }
    
    public void setNumMtotarjeta(BigDecimal numMtotarjeta) {
        this.numMtotarjeta = numMtotarjeta;
    }
    public BigDecimal getNumMtocomi() {
        return this.numMtocomi;
    }
    
    public void setNumMtocomi(BigDecimal numMtocomi) {
        this.numMtocomi = numMtocomi;
    }
    public BigDecimal getNumMtoefectivo() {
        return this.numMtoefectivo;
    }
    
    public void setNumMtoefectivo(BigDecimal numMtoefectivo) {
        this.numMtoefectivo = numMtoefectivo;
    }
    public String getCodSerie() {
        return this.codSerie;
    }
    
    public void setCodSerie(String codSerie) {
        this.codSerie = codSerie;
    }
    public BigDecimal getNumDocu() {
        return this.numDocu;
    }
    
    public void setNumDocu(BigDecimal numDocu) {
        this.numDocu = numDocu;
    }

    public String getNumDocuunido() {
        return numDocuunido;
    }

    public void setNumDocuunido(String numDocuunido) {
        this.numDocuunido = numDocuunido;
    }
    
    public BigDecimal getNumMtodscto() {
        return this.numMtodscto;
    }
    
    public void setNumMtodscto(BigDecimal numMtodscto) {
        this.numMtodscto = numMtodscto;
    }
    public BigDecimal getNumSubtotal() {
        return this.numSubtotal;
    }
    
    public void setNumSubtotal(BigDecimal numSubtotal) {
        this.numSubtotal = numSubtotal;
    }
    public BigDecimal getNumIgv() {
        return this.numIgv;
    }
    
    public void setNumIgv(BigDecimal numIgv) {
        this.numIgv = numIgv;
    }  

    public BigDecimal getNumMtovuelto() {
        return numMtovuelto;
    }

    public void setNumMtovuelto(BigDecimal numMtovuelto) {
        this.numMtovuelto = numMtovuelto;
    }

    public BigDecimal getIdSclaseeven() {
        return idSclaseeven;
    }

    public void setIdSclaseeven(BigDecimal idSclaseeven) {
        this.idSclaseeven = idSclaseeven;
    }

    public BigDecimal getIdPersexterno() {
        return idPersexterno;
    }

    public void setIdPersexterno(BigDecimal idPersexterno) {
        this.idPersexterno = idPersexterno;
    }    

    public List<Sic3docuprod> getLstSic3docuprod() {
        return lstSic3docuprod;
    }

    public void setLstSic3docuprod(List<Sic3docuprod> lstSic3docuprod) {
        this.lstSic3docuprod = lstSic3docuprod;
    }
        
    public Sic1idendocu getSic1idendocu() {
        return sic1idendocu;
    }
  
    public void setSic1idendocu(Sic1idendocu sic1idendocu) {
        this.sic1idendocu = sic1idendocu;
    }
    
    public BigDecimal getNumMtoTotal() {
        return numMtoTotal;
    }
    
    public void setNumMtoTotal(BigDecimal numMtoTotal) {
        this.numMtoTotal = numMtoTotal;
    }
    
    public Sic3docuesta getSic3docuesta() {
        return sic3docuesta;
    }

    public void setSic3docuesta(Sic3docuesta sic3docuesta) {
        this.sic3docuesta = sic3docuesta;
    }
    
    public String getCodEstadocu() {
        return codEstadocu;
    }

    public void setCodEstadocu(String codEstadocu) {
        this.codEstadocu = codEstadocu;
    }

    public Integer getFlgPrecsinIGV() {
        return flgPrecsinIGV;
    }

    public void setFlgPrecsinIGV(Integer flgPrecsinIGV) {
        this.flgPrecsinIGV = flgPrecsinIGV;
    }

    public Sic1pers getSic1perscontribuyente() {
        return sic1perscontribuyente;
    }

    public void setSic1perscontribuyente(Sic1pers sic1perscontribuyente) {
        this.sic1perscontribuyente = sic1perscontribuyente;
    }   

    public Sic1pers getSic1persexterno() {
        return sic1persexterno;
    }

    public void setSic1persexterno(Sic1pers sic1persexterno) {
        this.sic1persexterno = sic1persexterno;
    }

    public Sic1stipodocu getSic1stipodocu() {
        return sic1stipodocu;
    }

    public void setSic1stipodocu(Sic1stipodocu sic1stipodocu) {
        this.sic1stipodocu = sic1stipodocu;
    }

    public Sic1sclaseeven getSic1sclaseeven() {
        return sic1sclaseeven;
    }

    public void setSic1sclaseeven(Sic1sclaseeven sic1sclaseeven) {
        this.sic1sclaseeven = sic1sclaseeven;
    }

    public String getDesEstadocu() {
        return desEstadocu;
    }

    public void setDesEstadocu(String desEstadocu) {
        this.desEstadocu = desEstadocu;
    }

    public List<Sic3docudocu> getLstDocusPadre() {
        return lstDocusPadre;
    }

    public void setLstDocusPadre(List<Sic3docudocu> lstDocusPadre) {
        this.lstDocusPadre = lstDocusPadre;
    }

    public List<Sic3docudocu> getLstDocusHijo() {
        return lstDocusHijo;
    }

    public void setLstDocusHijo(List<Sic3docudocu> lstDocusHijo) {
        this.lstDocusHijo = lstDocusHijo;
    }        

    public Sic3docudocu getSic3docudocu() {
        return sic3docudocu;
    }

    public void setSic3docudocu(Sic3docudocu sic3docudocu) {
        this.sic3docudocu = sic3docudocu;
    }   

    public BigDecimal getNumMtocomitarjeta() {
        return numMtocomitarjeta;
    }

    public void setNumMtocomitarjeta(BigDecimal numMtocomitarjeta) {
        this.numMtocomitarjeta = numMtocomitarjeta;
    }

    public Double getNumMtoPagadoTarjeta() {
        return numMtoPagadoTarjeta;
    }

    public void setNumMtoPagadoTarjeta(Double numMtoPagadoTarjeta) {
        this.numMtoPagadoTarjeta = numMtoPagadoTarjeta;
    }

    public Double getNumMtoPagadoEfectivo() {
        return numMtoPagadoEfectivo;
    }

    public void setNumMtoPagadoEfectivo(Double numMtoPagadoEfectivo) {
        this.numMtoPagadoEfectivo = numMtoPagadoEfectivo;
    }

    public Double getNumMtoPagadoComiTarjeta() {
        return numMtoPagadoComiTarjeta;
    }

    public void setNumMtoPagadoComiTarjeta(Double numMtoPagadoComiTarjeta) {
        this.numMtoPagadoComiTarjeta = numMtoPagadoComiTarjeta;
    }

    public Sic1pers getSic1persregistrador() {
        return sic1persregistrador;
    }

    public void setSic1persregistrador(Sic1pers sic1persregistrador) {
        this.sic1persregistrador = sic1persregistrador;
    }

    public Sic1general getObjFormaPago() {
        return objFormaPago;
    }

    public void setObjFormaPago(Sic1general objFormaPago) {
        this.objFormaPago = objFormaPago;
    }

    public Sic1general getObjTipoTarjeta() {
        return objTipoTarjeta;
    }

    public void setObjTipoTarjeta(Sic1general objTipoTarjeta) {
        this.objTipoTarjeta = objTipoTarjeta;
    }

    public Sic1general getObjTipoNotaCredDebi() {
        return objTipoNotaCredDebi;
    }

    public void setObjTipoNotaCredDebi(Sic1general objTipoNotaCredDebi) {
        this.objTipoNotaCredDebi = objTipoNotaCredDebi;
    }   

    public Integer getIdSucursal() {
        return idSucursal;
    }

    public void setIdSucursal(Integer idSucursal) {
        this.idSucursal = idSucursal;
    }

    public String getNumVoucher() {
        return numVoucher;
    }

    public void setNumVoucher(String numVoucher) {
        this.numVoucher = numVoucher;
    }

    public Integer getFlgDeclaradosunat() {
        return flgDeclaradosunat;
    }

    public void setFlgDeclaradosunat(Integer flgDeclaradosunat) {
        this.flgDeclaradosunat = flgDeclaradosunat;
    }  

    public Sic1lugar getSic1lSucursal() {
        return sic1lSucursal;
    }

    public void setSic1lSucursal(Sic1lugar sic1lSucursal) {
        this.sic1lSucursal = sic1lSucursal;
    }         

    public String getCodTrolpersexterno() {
        return codTrolpersexterno;
    }

    public void setCodTrolpersexterno(String codTrolpersexterno) {
        this.codTrolpersexterno = codTrolpersexterno;
    }   

    public List<Sic3docupers> getLstPersRela() {
        return lstPersRela;
    }

    public void setLstPersRela(List<Sic3docupers> lstPersRela) {
        this.lstPersRela = lstPersRela;
    }  

    public Sic1docufacturadorsunat getSic1docufacturadorsunat() {
        return sic1docufacturadorsunat;
    }

    public void setSic1docufacturadorsunat(Sic1docufacturadorsunat sic1docufacturadorsunat) {
        this.sic1docufacturadorsunat = sic1docufacturadorsunat;
    }  
    
    public String toString(){
       return " idDocu: " + this.idDocu + 
              " desDocu: " + this.desDocu +
              " codSerie: " + this.codSerie +
              " numDocu: " + this.numDocu +
              " idPers: " + this.idPers +
              " idPrecsinIGV: " + this.flgPrecsinIGV +
              " idStipodocu: " + this.idStipodocu;
    }
}


