package com.general.hibernate.entity;
// Generated 27/02/2019 05:01:42 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Sic7persrolId generated by hbm2java
 */
public class Sic7persrolId  implements java.io.Serializable {


     private Date fecDesde;
     private Date fecHasta;
     private String desNotas;
     private BigDecimal idTrolpers;
     private BigDecimal idPers;

    public Sic7persrolId() {
    }

    public Sic7persrolId(Date fecDesde, Date fecHasta, String desNotas, BigDecimal idTrolpers, BigDecimal idPers) {
       this.fecDesde = fecDesde;
       this.fecHasta = fecHasta;
       this.desNotas = desNotas;
       this.idTrolpers = idTrolpers;
       this.idPers = idPers;
    }
   
    public Date getFecDesde() {
        return this.fecDesde;
    }
    
    public void setFecDesde(Date fecDesde) {
        this.fecDesde = fecDesde;
    }
    public Date getFecHasta() {
        return this.fecHasta;
    }
    
    public void setFecHasta(Date fecHasta) {
        this.fecHasta = fecHasta;
    }
    public String getDesNotas() {
        return this.desNotas;
    }
    
    public void setDesNotas(String desNotas) {
        this.desNotas = desNotas;
    }
    public BigDecimal getIdTrolpers() {
        return this.idTrolpers;
    }
    
    public void setIdTrolpers(BigDecimal idTrolpers) {
        this.idTrolpers = idTrolpers;
    }
    public BigDecimal getIdPers() {
        return this.idPers;
    }
    
    public void setIdPers(BigDecimal idPers) {
        this.idPers = idPers;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Sic7persrolId) ) return false;
		 Sic7persrolId castOther = ( Sic7persrolId ) other; 
         
		 return ( (this.getFecDesde()==castOther.getFecDesde()) || ( this.getFecDesde()!=null && castOther.getFecDesde()!=null && this.getFecDesde().equals(castOther.getFecDesde()) ) )
 && ( (this.getFecHasta()==castOther.getFecHasta()) || ( this.getFecHasta()!=null && castOther.getFecHasta()!=null && this.getFecHasta().equals(castOther.getFecHasta()) ) )
 && ( (this.getDesNotas()==castOther.getDesNotas()) || ( this.getDesNotas()!=null && castOther.getDesNotas()!=null && this.getDesNotas().equals(castOther.getDesNotas()) ) )
 && ( (this.getIdTrolpers()==castOther.getIdTrolpers()) || ( this.getIdTrolpers()!=null && castOther.getIdTrolpers()!=null && this.getIdTrolpers().equals(castOther.getIdTrolpers()) ) )
 && ( (this.getIdPers()==castOther.getIdPers()) || ( this.getIdPers()!=null && castOther.getIdPers()!=null && this.getIdPers().equals(castOther.getIdPers()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getFecDesde() == null ? 0 : this.getFecDesde().hashCode() );
         result = 37 * result + ( getFecHasta() == null ? 0 : this.getFecHasta().hashCode() );
         result = 37 * result + ( getDesNotas() == null ? 0 : this.getDesNotas().hashCode() );
         result = 37 * result + ( getIdTrolpers() == null ? 0 : this.getIdTrolpers().hashCode() );
         result = 37 * result + ( getIdPers() == null ? 0 : this.getIdPers().hashCode() );
         return result;
   }   


}


