package com.general.hibernate.entity;
// Generated 27/02/2019 05:01:42 PM by Hibernate Tools 4.3.1




/**
 * Sic7persrol generated by hbm2java
 */
public class Sic7persrol  implements java.io.Serializable {


    private Sic7persrolId id;
    
    /*Agregado*/
    private String codTrolpers;
    private String desTrolpers;

    public Sic7persrol() {
    }

    public Sic7persrol(Sic7persrolId id) {
       this.id = id;
    }
   
    public Sic7persrolId getId() {
        return this.id;
    }
    
    public void setId(Sic7persrolId id) {
        this.id = id;
    }

    public String getCodTrolpers() {
        return codTrolpers;
    }

    public void setCodTrolpers(String codTrolpers) {
        this.codTrolpers = codTrolpers;
    }

    public String getDesTrolpers() {
        return desTrolpers;
    }

    public void setDesTrolpers(String desTrolpers) {
        this.desTrolpers = desTrolpers;
    }




}


