package com.general.hibernate.entity;
// Generated 28/10/2017 06:46:21 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Sic8trela generated by hbm2java
 */
public class Sic8trela  implements java.io.Serializable {


     private BigDecimal idTrela;
     private String desTrela;
     private String codTrela;
     private BigDecimal idClaserela;
     private BigDecimal flgModocarga;
     private BigDecimal flgCreaeven;
     private BigDecimal idClaserelavers;
     private BigDecimal flgEliminado;
     private Set sic3lugarperses = new HashSet(0);

    public Sic8trela() {
    }

	
    public Sic8trela(BigDecimal idTrela, String codTrela, BigDecimal idClaserela, BigDecimal flgModocarga, BigDecimal flgCreaeven) {
        this.idTrela = idTrela;
        this.codTrela = codTrela;
        this.idClaserela = idClaserela;
        this.flgModocarga = flgModocarga;
        this.flgCreaeven = flgCreaeven;
    }
    public Sic8trela(BigDecimal idTrela, String desTrela, String codTrela, BigDecimal idClaserela, BigDecimal flgModocarga, BigDecimal flgCreaeven, BigDecimal idClaserelavers, BigDecimal flgEliminado, Set sic3lugarperses) {
       this.idTrela = idTrela;
       this.desTrela = desTrela;
       this.codTrela = codTrela;
       this.idClaserela = idClaserela;
       this.flgModocarga = flgModocarga;
       this.flgCreaeven = flgCreaeven;
       this.idClaserelavers = idClaserelavers;
       this.flgEliminado = flgEliminado;
       this.sic3lugarperses = sic3lugarperses;
    }
   
    public BigDecimal getIdTrela() {
        return this.idTrela;
    }
    
    public void setIdTrela(BigDecimal idTrela) {
        this.idTrela = idTrela;
    }
    public String getDesTrela() {
        return this.desTrela;
    }
    
    public void setDesTrela(String desTrela) {
        this.desTrela = desTrela;
    }
    public String getCodTrela() {
        return this.codTrela;
    }
    
    public void setCodTrela(String codTrela) {
        this.codTrela = codTrela;
    }
    public BigDecimal getIdClaserela() {
        return this.idClaserela;
    }
    
    public void setIdClaserela(BigDecimal idClaserela) {
        this.idClaserela = idClaserela;
    }
    public BigDecimal getFlgModocarga() {
        return this.flgModocarga;
    }
    
    public void setFlgModocarga(BigDecimal flgModocarga) {
        this.flgModocarga = flgModocarga;
    }
    public BigDecimal getFlgCreaeven() {
        return this.flgCreaeven;
    }
    
    public void setFlgCreaeven(BigDecimal flgCreaeven) {
        this.flgCreaeven = flgCreaeven;
    }
    public BigDecimal getIdClaserelavers() {
        return this.idClaserelavers;
    }
    
    public void setIdClaserelavers(BigDecimal idClaserelavers) {
        this.idClaserelavers = idClaserelavers;
    }
    public BigDecimal getFlgEliminado() {
        return this.flgEliminado;
    }
    
    public void setFlgEliminado(BigDecimal flgEliminado) {
        this.flgEliminado = flgEliminado;
    }
    public Set getSic3lugarperses() {
        return this.sic3lugarperses;
    }
    
    public void setSic3lugarperses(Set sic3lugarperses) {
        this.sic3lugarperses = sic3lugarperses;
    }




}


