package com.general.hibernate.temp;
// Generated 29/08/2018 05:15:18 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Sic4publcanalId generated by hbm2java
 */
public class Sic4publcanalId  implements java.io.Serializable {


     private BigDecimal numPeri;
     private BigDecimal idPublcanal;

    public Sic4publcanalId() {
    }

    public Sic4publcanalId(BigDecimal numPeri, BigDecimal idPublcanal) {
       this.numPeri = numPeri;
       this.idPublcanal = idPublcanal;
    }
   
    public BigDecimal getNumPeri() {
        return this.numPeri;
    }
    
    public void setNumPeri(BigDecimal numPeri) {
        this.numPeri = numPeri;
    }
    public BigDecimal getIdPublcanal() {
        return this.idPublcanal;
    }
    
    public void setIdPublcanal(BigDecimal idPublcanal) {
        this.idPublcanal = idPublcanal;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Sic4publcanalId) ) return false;
		 Sic4publcanalId castOther = ( Sic4publcanalId ) other; 
         
		 return ( (this.getNumPeri()==castOther.getNumPeri()) || ( this.getNumPeri()!=null && castOther.getNumPeri()!=null && this.getNumPeri().equals(castOther.getNumPeri()) ) )
 && ( (this.getIdPublcanal()==castOther.getIdPublcanal()) || ( this.getIdPublcanal()!=null && castOther.getIdPublcanal()!=null && this.getIdPublcanal().equals(castOther.getIdPublcanal()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNumPeri() == null ? 0 : this.getNumPeri().hashCode() );
         result = 37 * result + ( getIdPublcanal() == null ? 0 : this.getIdPublcanal().hashCode() );
         return result;
   }   


}


