package com.general.hibernate.temp;
// Generated 20/02/2018 11:01:48 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Sic4cuaddiarioId generated by hbm2java
 */
public class Sic4cuaddiarioId  implements java.io.Serializable {


     private BigDecimal idPers;
     private BigDecimal numPeri;

    public Sic4cuaddiarioId() {
    }

    public Sic4cuaddiarioId(BigDecimal idPers, BigDecimal numPeri) {
       this.idPers = idPers;
       this.numPeri = numPeri;
    }
   
    public BigDecimal getIdPers() {
        return this.idPers;
    }
    
    public void setIdPers(BigDecimal idPers) {
        this.idPers = idPers;
    }
    public BigDecimal getNumPeri() {
        return this.numPeri;
    }
    
    public void setNumPeri(BigDecimal numPeri) {
        this.numPeri = numPeri;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Sic4cuaddiarioId) ) return false;
		 Sic4cuaddiarioId castOther = ( Sic4cuaddiarioId ) other; 
         
		 return ( (this.getIdPers()==castOther.getIdPers()) || ( this.getIdPers()!=null && castOther.getIdPers()!=null && this.getIdPers().equals(castOther.getIdPers()) ) )
 && ( (this.getNumPeri()==castOther.getNumPeri()) || ( this.getNumPeri()!=null && castOther.getNumPeri()!=null && this.getNumPeri().equals(castOther.getNumPeri()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdPers() == null ? 0 : this.getIdPers().hashCode() );
         result = 37 * result + ( getNumPeri() == null ? 0 : this.getNumPeri().hashCode() );
         return result;
   }   


}


