package com.general.hibernate.temp;
// Generated 29/08/2018 05:15:18 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Sic4publcanal generated by hbm2java
 */
public class Sic4publcanal  implements java.io.Serializable {


     private Sic4publcanalId id;
     private BigDecimal idPers;
     private Date fecCreacion;
     private BigDecimal numPuntos;
     
     /*Agregado*/
     
     private String desPublCanal;

    public Sic4publcanal() {
    }

	
    public Sic4publcanal(Sic4publcanalId id, BigDecimal idPers) {
        this.id = id;
        this.idPers = idPers;
    }
    public Sic4publcanal(Sic4publcanalId id, BigDecimal idPers, Date fecCreacion, BigDecimal numPuntos) {
       this.id = id;
       this.idPers = idPers;
       this.fecCreacion = fecCreacion;
       this.numPuntos = numPuntos;
    }
   
    public Sic4publcanalId getId() {
        return this.id;
    }
    
    public void setId(Sic4publcanalId id) {
        this.id = id;
    }
    public BigDecimal getIdPers() {
        return this.idPers;
    }
    
    public void setIdPers(BigDecimal idPers) {
        this.idPers = idPers;
    }
    public Date getFecCreacion() {
        return this.fecCreacion;
    }
    
    public void setFecCreacion(Date fecCreacion) {
        this.fecCreacion = fecCreacion;
    }
    public BigDecimal getNumPuntos() {
        return this.numPuntos;
    }
    
    public void setNumPuntos(BigDecimal numPuntos) {
        this.numPuntos = numPuntos;
    }

    public String getDesPublCanal() {
        return desPublCanal;
    }

    public void setDesPublCanal(String desPublCanal) {
        this.desPublCanal = desPublCanal;
    }

    


}


